(function () {
  "use strict";

  const APP_CONFIG = {
    planId: "rehab_foundation_2026_07_27",
    planVersion: 1,
    planName: "Herstel- en fundamentprogramma — 8 weken",
    planSubtitle: "Serieuze krachttraining, progressieve revalidatie en gecontroleerde loopopbouw",
    sourceFile: "herstel_en_fundamentprogramma_8_weken.txt",
    startDate: "2026-07-27",
    endDate: "2026-09-20",
    startCalendarWeek: 31,
    marathonDate: "2026-11-22",
    version: "2026.07.27.rehab-foundation.1",
    description:
      "Dit tijdelijke achtweekse programma maakt schouders, golfersellebogen, brachialis/elleboogflexoren, heupen, benen, kuiten en enkels belastbaarder. Het combineert serieuze krachttraining, isometrische en dynamische revalidatie en drie looptrainingen per week.",
    continuationNotice:
      "Dit herstel- en fundamentblok is afgerond. Voor de resterende periode richting de marathon is een nieuw vervolgschema nodig.",
    marathonNuance:
      "Dit is een tijdelijk herstel- en fundamentblok. Drie runs van ongeveer dertig minuten vormen nog geen volledige marathonvoorbereiding. Na vier tot zes weken moet worden beoordeeld of één looptraining geleidelijk langer kan worden; na week 8 is een nieuw marathonspecifiek vervolgblok nodig.",
  };

  const GENERAL_RULES = {
    painScale: [
      "0–2/10: prima; de beweging mag normaal worden uitgevoerd.",
      "3/10: meestal acceptabel als de pijn stabiel blijft en de techniek niet verandert.",
      "4/10: verminder gewicht, bewegingsuitslag, holdduur of totaal volume.",
      "5/10 of hoger: stop de oefening of kies een vervanging.",
      "Stop direct bij scherpe of plotselinge pijn, tintelingen, gevoelloosheid of merkbaar krachtverlies.",
      "De volgende ochtend hoort de klacht ongeveer terug te zijn op het oude uitgangsniveau. Duidelijk meer pijn betekent dat de totale dosis te groot was.",
    ],
    doubleProgression: [
      "Kies bij 3 × 8–12 een gewicht waarmee bijvoorbeeld 10, 9 en 8 nette herhalingen mogelijk zijn.",
      "Behoud het gewicht totdat 12, 12 en 12 technisch goed lukt.",
      "Verhoog daarna met de kleinste beschikbare stap en bouw opnieuw op vanaf lagere herhalingen.",
      "Kleine schouder- en onderarmoefeningen: meestal 0,5–1 kg. Kabel: één kleine stap. Beenmachines: ongeveer 2,5–10 kg. Unilateraal: liever kleine stappen.",
    ],
    isometricProgression: [
      "Verhoog eerst de holdduur van ongeveer 20 naar 30 en vervolgens 40 seconden.",
      "Verhoog pas daarna het gewicht of de kabelweerstand.",
      "Gebruik eventueel later een tweede gewrichtshoek.",
      "Verhoog nooit tegelijk duur, gewicht én aantal sets.",
    ],
  };

  const PHASES = [
    {
      phaseId: "fase-1",
      phaseName: "Fase 1 — Kalibreren",
      weekRange: "Programmaweek 1–2",
      startDate: "2026-07-27",
      endDate: "2026-08-09",
      goal: "Techniek leren, pijnreacties beoordelen en een veilige maar serieuze uitgangsbelasting vinden.",
      structure: "Vier sessies per week: één volledige krachttraining en drie 30/30-hybride sessies.",
      rules:
        "Dynamische revalidatie RIR 3–4, isometrische holds 5–6/10 en alle runs volledig easy. Nog geen overhead press, pull-ups, chin-ups, zware vrije rows of gewone zware curls.",
      phaseDetails: {
        runsPerWeek: "3 × ongeveer 30 min easy",
        gymPerWeek: "4 kracht-/revalidatieprikkels",
        primaryGoal: "Techniek, tolerantie en geschikte startgewichten vaststellen zonder automatisch licht te blijven trainen.",
        stats: ["RIR 3–4 dynamisch", "holds 5–6/10", "3 easy runs", "overhead press nog niet"],
        sections: [
          {
            title: "Kracht en revalidatie",
            text: "De bewegingen worden technisch aangeleerd en serieus maar beheerst belast. Het doel is niet pijnvrij bewegen tegen elke prijs, maar een dosis vinden die tijdens de training verdraagbaar is en de volgende ochtend weer op uitgangsniveau zit.",
          },
          {
            title: "Hardlopen",
            text: "Alle drie de runs blijven volledig easy op RPE 3–4. Je moet volledige zinnen kunnen spreken. Er is nog geen interval- of progressionprikkel.",
          },
          {
            title: "Isometrisch",
            text: "Holds voelen stevig maar nooit maximaal. Blijf ademen en stop voordat de houding langzaam instort.",
          },
          {
            title: "Terugkeerstatus",
            text: "Nog geen overhead press, pull-ups, chin-ups, zware vrije rows of gewone zware curls. Eerst twee stabiele weken opbouwen.",
          },
          {
            title: "Wat moet dit opleveren?",
            text: "Correcte uitvoering, inzicht in dezelfde-dag- en volgende-ochtendreacties, eerste stabiele belastbaarheid en passende startgewichten.",
          },
        ],
      },
    },
    {
      phaseId: "fase-2",
      phaseName: "Fase 2 — Belasting opbouwen",
      weekRange: "Programmaweek 3–5",
      startDate: "2026-08-10",
      endDate: "2026-08-30",
      goal: "Dynamische weerstand verhogen, lopen voorzichtig intensiveren en gecontroleerd terugkeren naar functionelere bewegingen.",
      structure: "Dezelfde vier sessies, met hogere weerstand en één gecontroleerd snellere looptraining.",
      rules:
        "Dynamisch RIR 2–3; holds 30–40 sec en 6–7/10. Landmine press alleen als de criteria zijn gehaald. Grip en curls gecontroleerd opbouwen.",
      phaseDetails: {
        runsPerWeek: "3 × ongeveer 30 min",
        gymPerWeek: "4 kracht-/revalidatieprikkels",
        primaryGoal: "Meer dynamische kracht en belastbaarheid opbouwen zonder de pijn- en herstelregels los te laten.",
        stats: ["RIR 2–3 dynamisch", "holds 30–40 sec", "conditionele strides", "1 gecontroleerde snellere run"],
        sections: [
          {
            title: "Kracht en revalidatie",
            text: "Wanneer de bovengrens technisch goed wordt gehaald en de reactie de volgende ochtend rustig is, gaat het gewicht omhoog. Revalidatie blijft dus niet permanent licht.",
          },
          {
            title: "Hardlopen",
            text: "Dag 2 krijgt alleen bij twee stabiele heupweken vier ontspannen versnellingen. Dag 3 bevat een gecontroleerde RPE-6-prikkel; Dag 4 eindigt geleidelijk wat vlotter.",
          },
          {
            title: "Grip en elleboogflexie",
            text: "Curls met cuff worden zwaarder. Vanaf week 4–6 kan een losse neutrale kabelgreep worden getest als hard knijpen de elleboog niet irriteert.",
          },
          {
            title: "Overhead press",
            text: "De half-kneeling landmine press mag alleen worden geïntroduceerd als schoudertraining twee weken stabiel is, incline push-ups maximaal 2/10 geven en er geen extra napijn of krachtverlies is.",
          },
          {
            title: "Wat moet dit opleveren?",
            text: "Hogere belastbaarheid, langere stabiele holds, meer dynamische kracht en een eerste beheerste terugkeer naar normale grip en drukbewegingen.",
          },
        ],
      },
    },
    {
      phaseId: "fase-3",
      phaseName: "Fase 3 — Sterkte en terugkeer voorbereiden",
      weekRange: "Programmaweek 6–8",
      startDate: "2026-08-31",
      endDate: "2026-09-20",
      goal: "Oefeningen serieus verzwaren, functionele kracht herstellen en terugkeer naar overhead- en trekbewegingen voorbereiden.",
      structure: "Dezelfde vier sessies met RIR 2 als richtpunt en voorwaardelijke terugkeerstappen.",
      rules:
        "Grote beenoefeningen RIR 2, kleine dynamische oefeningen meestal RIR 2 en holds 7–8/10. Geen maximale pull-ups, zware vrije rows of maximale gewone curls.",
      phaseDetails: {
        runsPerWeek: "3 × ongeveer 30 min",
        gymPerWeek: "4 kracht-/revalidatieprikkels",
        primaryGoal: "Substantiële belastbaarheid bereiken en een veilige basis leggen voor het volgende marathonspecifieke blok.",
        stats: ["grote beenoefeningen RIR 2", "holds 7–8/10", "3 × 4 min gecontroleerd", "overhead alleen conditioneel"],
        sections: [
          {
            title: "Kracht en revalidatie",
            text: "Grote beenoefeningen en kleine revalidatiebewegingen mogen serieus zwaar worden zolang uitvoering, pijnreactie en herstel stabiel blijven.",
          },
          {
            title: "Hardlopen",
            text: "Dag 3 bevat drie gecontroleerde stukken van vier minuten op RPE 6–7. Dag 2 en Dag 4 blijven technisch soepel en niet maximaal.",
          },
          {
            title: "Overhead press",
            text: "De machine overhead press mag pas worden getest na twee probleemloze weken landmine press. Start op 2 × 10–12 met RIR 4.",
          },
          {
            title: "Grip en trekken",
            text: "Grip wordt geleidelijk teruggebracht, maar maximale pull-ups, zware vrije rows en maximale gewone curls blijven buiten dit blok.",
          },
          {
            title: "Wat moet dit opleveren?",
            text: "Sterkere schouders, ellebogen, benen en kuiten, gecontroleerde terugkeer naar overheadwerk en een betere basis voor een nieuw marathonspecifiek vervolgplan.",
          },
        ],
      },
    },
  ];

  const basePain = [
    "Gebruik de algemene 0–5/10-pijnschaal: tot 3/10 kan verdraagbaar zijn als het stabiel blijft; bij 4/10 aanpassen en bij 5/10 stoppen.",
    "Stop direct bij scherpe pijn, tintelingen, gevoelloosheid of onverwacht krachtverlies.",
    "Controleer de volgende ochtend: de klacht hoort ongeveer terug te zijn op het oude uitgangsniveau.",
  ];

  function detail(config) {
    return {
      purpose: config.purpose,
      muscles: config.muscles || [],
      why: config.why,
      setup: config.setup || [],
      execution: config.execution || [],
      posture: config.posture || [],
      feel: config.feel || "",
      mistakes: config.mistakes || [],
      painRules: config.painRules || basePain,
      progression: config.progression || GENERAL_RULES.doubleProgression,
      regression: config.regression || [],
      alternatives: config.alternatives || [],
      phaseDifferences:
        config.phaseDifferences || [
          "Week 1–2: techniek en reactie kalibreren; dynamisch meestal RIR 3–4.",
          "Week 3–5: naar RIR 2–3 en weerstand verhogen als de bovengrens technisch goed lukt.",
          "Week 6–8: meestal RIR 2, zonder falen of compensatie.",
        ],
      cue: config.cue || "Beweeg gecontroleerd en houd de afgesproken positie vast.",
    };
  }

  const EXERCISE_DETAILS = {
    "warmup-bike-walk": detail({
      purpose: "Lichaamstemperatuur en doorbloeding verhogen zonder vermoeidheid op te bouwen.",
      muscles: ["Benen en heupen licht actief", "hart-longstelsel", "enkels in rustige cyclische beweging"],
      why: "Een korte algemene warming-up maakt de eerste krachtbewegingen soepeler zonder energie weg te nemen van de werksets.",
      setup: ["Kies fiets of loopband/wandelruimte.", "Gebruik een zeer lichte weerstand en een tempo waarbij praten eenvoudig blijft."],
      execution: ["Beweeg drie minuten gelijkmatig.", "Laat het tempo in de laatste minuut iets vloeiender worden, niet zwaarder."],
      posture: ["Romp ontspannen lang.", "Schouders laag en handen los.", "Normaal doorademen."],
      feel: "Licht warmer en losser, niet buiten adem of vermoeid.",
      mistakes: ["Te hard starten.", "Hoge weerstand kiezen.", "Van de warming-up een conditietest maken."],
      progression: ["Geen echte progressie nodig; drie rustige minuten blijven voldoende."],
      regression: ["Rustiger wandelen of minder fietsweerstand."],
      alternatives: ["Rustig roeien als schouder en elleboog dat probleemloos verdragen."],
      cue: "Warm worden, niet moe worden.",
    }),
    "bodyweight-squat": detail({
      purpose: "Knie-, heup- en enkelbeweging voorbereiden op de zware beenoefeningen.",
      muscles: ["Quadriceps", "bilspieren", "adductoren", "rompstabilisatoren"],
      why: "De oefening laat je vóór belasting controleren of voetdruk, kniespoor en heupdiepte vandaag rustig voelen.",
      setup: ["Voeten ongeveer schouderbreed.", "Tenen licht naar buiten als dat natuurlijk voelt.", "Armen voor je voor balans."],
      execution: ["Zak rustig tussen je heupen.", "Houd de hele voet op de grond.", "Duw gecontroleerd terug omhoog."],
      posture: ["Knieën volgen tenen.", "Ribben boven bekken.", "Geen geforceerde diepte."],
      feel: "Lichte activiteit in bovenbenen en billen; gewrichten horen vrij te bewegen.",
      mistakes: ["Hielen optillen.", "Knieën naar binnen laten vallen.", "Snel in de onderste positie stuiteren."],
      progression: ["Blijft een warming-up: verbeter controle, voeg geen vermoeiend gewicht toe."],
      regression: ["Minder diep zakken of een bank als diepte-doel gebruiken."],
      alternatives: ["Sit-to-stand vanaf een bank."],
      cue: "Hele voet zwaar op de vloer.",
    }),
    "glute-bridge": detail({
      purpose: "Bilspieren en bekkencontrole activeren voor hip thrusts, split squats en hardlopen.",
      muscles: ["Gluteus maximus", "hamstrings secundair", "rompstabilisatoren"],
      why: "Geeft een eenvoudige eerste heupextensieprikkel zonder grip of zware gewrichtsbelasting.",
      setup: ["Rug op de vloer, knieën gebogen.", "Voeten ongeveer heupbreed en dicht genoeg dat de schenen bovenin bijna verticaal zijn."],
      execution: ["Kantel het bekken licht achterover.", "Duw via hielen en middenvoet omhoog.", "Stop bij gestrekte heupen en zak rustig."],
      posture: ["Ribben laag.", "Geen overmatige holling in de onderrug.", "Knieën blijven boven de voeten."],
      feel: "Vooral spanning in de billen, niet een knijpende sensatie voorin de heup.",
      mistakes: ["Te hoog komen via de onderrug.", "Voeten te ver weg zetten.", "Knieën naar buiten of binnen laten wijken."],
      progression: ["Blijft een rustige warming-up; maak de aanspanning bewuster in plaats van zwaarder."],
      regression: ["Kleinere bewegingsuitslag."],
      alternatives: ["Staande bilspier-aanspanning."],
      cue: "Riemgesp richting gezicht.",
    }),
    "scapular-push-up": detail({
      purpose: "Schouderbladcontrole en serratusactivatie voorbereiden zonder de ellebogen te buigen.",
      muscles: ["Serratus anterior", "schouderbladstabilisatoren", "core"],
      why: "Helpt de schouderbladen leren bewegen over de ribbenkast in plaats van ze voortdurend vast naar achteren te trekken.",
      setup: ["Handen onder of iets breder dan schouders.", "Knieën of voeten op de vloer.", "Ellebogen gestrekt maar niet hard op slot."],
      execution: ["Laat de borst licht tussen de schouders zakken.", "Duw daarna de vloer weg zodat de schouderbladen uit elkaar bewegen.", "Houd de beweging klein en rustig."],
      posture: ["Romp als één lijn.", "Geen holle onderrug.", "Schouders niet naar de oren trekken."],
      feel: "Activiteit langs de zijkant van de ribbenkast en rond de schouderbladen.",
      mistakes: ["Ellebogen buigen.", "Hoofd naar voren steken.", "De plus maken door alleen de bovenrug extreem bol te trekken."],
      progression: ["Van knieën naar voeten als warming-upcontrole goed blijft."],
      regression: ["Staand tegen een muur."],
      alternatives: ["Wall slide zonder gewicht."],
      cue: "Duw de vloer rustig van je af.",
    }),
    "hip-circles": detail({
      purpose: "Heupgewrichten rustig door beschikbare bewegingsrichtingen bewegen.",
      muscles: ["Diepe heupspieren", "heupflexoren", "bilspieren", "adductoren"],
      why: "Geeft vóór beenkracht een korte controle van heupmobiliteit zonder te claimen dat stijfheid de enige oorzaak van klachten is.",
      setup: ["Sta rechtop en houd eventueel licht steun.", "Bekken blijft zoveel mogelijk stil."],
      execution: ["Til één knie op.", "Maak een kleine gecontroleerde cirkel vanuit de heup.", "Voer vijf herhalingen per kant uit."],
      posture: ["Romp lang.", "Niet meedraaien met de onderrug.", "Beweging blijft pijnvrij of maximaal licht gevoelig."],
      feel: "Rustige beweging rondom de heup, geen scherpe diepe liespijn.",
      mistakes: ["Grote snelle cirkels.", "Bekken volledig meedraaien.", "Door een knelpunt heen forceren."],
      progression: ["Iets vloeiender of iets groter bewegen, niet sneller."],
      regression: ["Kleinere cirkel of zittend uitvoeren."],
      alternatives: ["90/90 hip switches in de mobiliteitsroutine."],
      cue: "Kleine cirkel, stil bekken.",
    }),
    "arm-circles": detail({
      purpose: "Schouders en armen rustig voorbereiden op rotator-cuff- en hefbewegingen.",
      muscles: ["Deltoideus licht", "rotator cuff", "schouderbladspieren"],
      why: "Een korte dynamische voorbereiding laat zien welke bewegingshoek vandaag comfortabel is.",
      setup: ["Sta lang met ontspannen armen.", "Begin met kleine cirkels."],
      execution: ["Maak tien rustige cirkels voorwaarts en tien achterwaarts.", "Vergroot alleen als dit soepel blijft."],
      posture: ["Ribben boven bekken.", "Geen shrug.", "Normaal ademen."],
      feel: "Losse, warme schouders zonder scherpe voorzijdepijn.",
      mistakes: ["Te snel zwaaien.", "Ribben naar voren duwen.", "Door pijnlijke hoeken forceren."],
      progression: ["Iets grotere maar altijd rustige cirkels."],
      regression: ["Kleinere cirkels of één arm tegelijk."],
      alternatives: ["Pendelbewegingen met ontspannen arm."],
      cue: "Rustig groter, nooit forceren.",
    }),
    "wall-slide-unweighted": detail({
      purpose: "Opwaartse rotatie van het schouderblad voorbereiden zonder externe weerstand.",
      muscles: ["Serratus anterior", "onderste en bovenste trapezius", "rotator cuff"],
      why: "Bereidt de serratus wall slide voor en leert dat schouderbladen tijdens armheffen mogen meebewegen.",
      setup: ["Onderarmen tegen de muur.", "Voeten een halve stap naar achteren.", "Geen gewicht of band."],
      execution: ["Schuif de armen rustig omhoog.", "Laat schouderbladen natuurlijk opwaarts draaien.", "Kom terug voordat controle verloren gaat."],
      posture: ["Ribben boven bekken.", "Geen holle rug.", "Schouders niet geforceerd omlaag trekken."],
      feel: "Lichte activiteit rond schouderbladen, geen knijpende pijn voorin de schouder.",
      mistakes: ["Onderrug hol trekken.", "Schouderbladen vastknijpen.", "Armen hoger duwen dan controle toelaat."],
      progression: ["Later foamroller en miniband gebruiken in de werksets."],
      regression: ["Kortere bewegingsuitslag."],
      alternatives: ["Scapular push-up tegen muur."],
      cue: "Laat het schouderblad omhoog meedraaien.",
    }),
    "warmup-set-first-exercise": detail({
      purpose: "De eerste werkbeweging en gekozen kabelweerstand testen voordat de echte sets starten.",
      muscles: ["Dezelfde spieren als de eerste oefening, maar met lage belasting"],
      why: "Maakt het makkelijker om een geschikt daggewicht te kiezen en onverwachte irritatie vroeg te herkennen.",
      setup: ["Stel kabel en cuff exact in zoals bij de eerste oefening.", "Kies duidelijk minder weerstand dan je werkgewicht."],
      execution: ["Voer 8–12 rustige herhalingen uit.", "Gebruik de volledige comfortabele beweging.", "Evalueer techniek en sensatie."],
      posture: ["Zelfde technische regels als de werkset.", "Normaal ademen.", "Geen compensatie toestaan omdat het 'maar warming-up' is."],
      feel: "Licht en voorbereid, niet vermoeid.",
      mistakes: ["De opwarmset te zwaar maken.", "Snel bewegen.", "Een onprettige reactie negeren."],
      progression: ["Geen progressiedoel; pas het werkgewicht aan op basis van deze set."],
      regression: ["Nog lichtere kabelstand of kortere bewegingsuitslag."],
      alternatives: ["Eén korte lichte isometrische proefhold."],
      cue: "Test de beweging, bewijs niets.",
    }),
    "iso-cable-external-rotation": detail({
      purpose: "Gecontroleerde isometrische rotator-cuffkracht opbouwen in een verdraagbare schouderhoek.",
      muscles: ["Infraspinatus", "teres minor", "achterste deltoideus secundair", "rotator-cuffpees en schouderstabilisatoren"],
      why: "De hold belast de buitenrotatoren zonder door een mogelijk gevoelige bewegingsfase te hoeven gaan. Een polsmanchet beperkt grijpen en ontziet daarmee de golferselleboog.",
      setup: ["Kabel op ellebooghoogte.", "Zij naar het station.", "Elleboog ongeveer 90° gebogen naast de romp.", "Eventueel handdoek tussen elleboog en romp.", "Bij ellebooggevoeligheid een polsmanchet gebruiken."],
      execution: ["Draai de onderarm een klein stukje naar buiten.", "Stop in een stevige maar niet scherpe positie.", "Houd 25–40 seconden tegen de kabel.", "Wissel van arm en blijf normaal ademen."],
      posture: ["Bovenarm blijft rustig.", "Ribben boven bekken.", "Schouder niet optrekken.", "Niet met de romp meedraaien of het schouderblad hard naar achteren trekken."],
      feel: "Spanning achter en aan de zijkant van de schouder; geen stekende pijn voorin.",
      mistakes: ["Maximaal naar buiten draaien.", "Adem vasthouden.", "Schouder richting oor trekken.", "Romp wegdraaien.", "Hold laten instorten."],
      progression: GENERAL_RULES.isometricProgression,
      regression: ["Korter vasthouden.", "Kabel één stap lichter.", "Kleinere buitenrotatiehoek.", "Cuff gebruiken in plaats van handgreep."],
      alternatives: ["Isometrische buitenrotatie tegen een muur", "lichte band-isometrie"],
      phaseDifferences: ["Week 1–2: 25–30 sec op 5–6/10.", "Week 3–5: 30–40 sec op 6–7/10.", "Week 6–8: tot 7–8/10; pas gewicht verhogen nadat 3 × 40 sec stabiel is."],
      cue: "Ribben stil, onderarm naar buiten, blijf ademen.",
    }),
    "iso-wrist-flexion": detail({
      purpose: "De polsflexoren en hun mediale elleboogaanhechting gecontroleerd zwaar leren belasten.",
      muscles: ["Flexor carpi radialis/ulnaris", "palmaris longus", "vingerflexoren secundair", "gemeenschappelijke flexorpees bij de golferselleboog"],
      why: "Isometrie maakt een stevige peesbelasting mogelijk met weinig beweging. Het is een opstap naar langzame dynamische polsflexie en pronatie-/supinatiebelasting.",
      setup: ["Zittend, onderarm volledig op bovenbeen of bank.", "Handpalm omhoog.", "Pols net voorbij de rand.", "Dumbbell vasthouden en pols licht optillen, niet maximaal krullen."],
      execution: ["Houd de pols 30–45 seconden stil.", "Knijp alleen zo hard als nodig.", "Laat elleboog en onderarm ondersteund.", "Gebruik de andere hand niet tijdens de hold."],
      posture: ["Pols in lijn met onderarm of licht gebogen.", "Schouders ontspannen.", "Normaal ademen."],
      feel: "Stevige spanning in de onderarmflexoren; hoogstens stabiele lichte gevoeligheid aan de binnenzijde van de elleboog.",
      mistakes: ["Volledig naar binnen krullen.", "Hard knijpen.", "Schokken.", "Met de andere hand helpen.", "Stekende pijn precies op het bot negeren."],
      progression: GENERAL_RULES.isometricProgression,
      regression: ["Lichtere dumbbell.", "Kortere hold.", "Pols dichter bij neutraal.", "Minder hard grijpen."],
      alternatives: ["Isometrische polsflexie tegen de andere hand", "kabel met polsmanchet indien beschikbaar"],
      phaseDifferences: ["Week 1–2: 30 sec en 5–6/10.", "Week 3–5: 30–40 sec en 6–7/10.", "Week 6–8: 40–45 sec of meer gewicht, maximaal 7–8/10."],
      cue: "Houd de pols stil; knijp niet harder dan nodig.",
    }),
    "hack-squat-or-leg-press": detail({
      purpose: "De belangrijkste zware knie- en heupstrekprikkel van de week leveren.",
      muscles: ["Quadriceps primair", "gluteus maximus", "adductoren", "hamstrings en kuiten stabiliserend", "knie- en heupstructuren"],
      why: "Hack squat en leg press laten substantiële beenbelasting toe met veel stabiliteit en zonder zware grip. Je kiest één variant; het zijn alternatieven binnen hetzelfde blok.",
      setup: ["Kies in de logger Hack squat of Leg press.", "Voeten ongeveer schouderbreed en volledig op het platform.", "Tenen licht naar buiten.", "Plaats voeten zo dat hielen onderin blijven staan.", "Rug en bekken tegen de steun."],
      execution: ["Adem in en span de buik.", "Zak in 2–3 seconden.", "Laat knieën de tenen volgen.", "Stop vóór bekkenverlies of scherpe heuppijn.", "Duw via de hele voet omhoog en vermijd agressieve lock-out."],
      posture: ["Volledige voetdruk.", "Knieën in lijn met tweede/derde teen.", "Bekken blijft gecontroleerd.", "Geen hard ontspannen onderin."],
      feel: "Zware spanning in bovenbenen en billen; geen scherpe voorste-heup- of kniepijn.",
      mistakes: ["Hielen los.", "Knieën naar binnen.", "Bekken sterk onderrollen.", "Onderin hangen.", "Adem de hele set vasthouden.", "Beide varianten als twee verplichte oefeningen uitvoeren."],
      progression: ["4 × 5–8 op RIR 2–3.", "Wanneer 4 × 8 met ongeveer RIR 2 lukt: verhoog 5–10 kg totaal of de kleinste machinestap.", "Behoud diepte en kniespoor na de verhoging."],
      regression: ["Minder diepte.", "Lichter gewicht.", "Leg press kiezen als hack squat de heup irriteert.", "Voetpositie licht aanpassen zonder de voetdruk te verliezen."],
      alternatives: ["Hack squat", "45° leg press", "horizontale leg press"],
      phaseDifferences: ["Week 1–2: techniek en passend startgewicht, RIR 2–3.", "Week 3–5: progressie zodra 4 × 8 technisch lukt.", "Week 6–8: meestal RIR 2, nooit tot falen."],
      cue: "Zak gecontroleerd en duw via je hele voet.",
    }),
    "hip-thrust-machine": detail({
      purpose: "Zware heupextensiekracht opbouwen met weinig gripbelasting.",
      muscles: ["Gluteus maximus primair", "hamstrings en adductoren secundair", "romp- en bekkenstabilisatoren"],
      why: "Sterke bilspieren ondersteunen hardlopen en beenkracht, terwijl de machine ellebogen en grip nauwelijks belast.",
      setup: ["Steun over het zachte deel van de heupen, niet de buik.", "Voeten zo dat schenen bovenin ongeveer verticaal zijn.", "Rug stevig tegen de steun."],
      execution: ["Kantel het bekken licht achterover.", "Duw via hielen en middenvoet omhoog.", "Stop bij gestrekte heupen.", "Houd één seconde en zak gecontroleerd."],
      posture: ["Ribben laag.", "Geen extra hoogte zoeken via een holle onderrug.", "Knieën blijven stabiel boven voeten."],
      feel: "Sterke bilspiercontractie bovenin; geen druk in onderrug of scherpe voorste-heuppijn.",
      mistakes: ["Te hoog doorstrekken.", "Voeten verkeerd plaatsen.", "Naar tenen duwen.", "Gewicht laten vallen."],
      progression: ["Bouw naar 3 × 10 op RIR 2.", "Verhoog daarna één machineplaat of ongeveer 5 kg.", "Keer terug naar 6–8 nette reps."],
      regression: ["Lichter gewicht.", "Kleinere range.", "Glute bridge op vloer."],
      alternatives: ["Barbell hip thrust met comfortabele pad", "weighted glute bridge"],
      cue: "Riemgesp omhoog; stop als de heup gestrekt is.",
    }),
    "leg-curl": detail({
      purpose: "Hamstrings dynamisch versterken door kniebuiging en gecontroleerde excentrische belasting.",
      muscles: ["Biceps femoris", "semitendinosus", "semimembranosus", "kuitspier secundair"],
      why: "Hamstringkracht ondersteunt loopbelasting en vormt een tweede serieuze beenprikkel zonder gripbelasting.",
      setup: ["Kies seated of lying variant.", "Lijn de machinedraaias zo goed mogelijk uit met de knie.", "Fixeer heupen tegen zitting of bank.", "Pad net boven de hiel/onderaan het onderbeen."],
      execution: ["Buig in ongeveer 2 seconden.", "Knijp één seconde in de eindpositie.", "Laat in 3 seconden terugkomen.", "Behoud een volledige comfortabele range."],
      posture: ["Heupen blijven tegen de steun.", "Geen schok uit de romp.", "Onderrug niet sterk hol trekken."],
      feel: "Spanning over de achterkant van het bovenbeen; geen scherpe knie- of peespijn.",
      mistakes: ["Halve reps voor meer gewicht.", "Gewicht terug laten vallen.", "Heupen optillen.", "Tempo versnellen.", "Door kramp heen drukken."],
      progression: ["3 × 8–12 met dubbele progressie.", "Op Dag 3 mag hetzelfde patroon iets lichter op RIR 2–3.", "Verhoog pas als het langzame terugzakken intact blijft."],
      regression: ["Lichter gewicht.", "Minder range.", "Eenbenig met nog minder gewicht als asymmetrie controle vraagt."],
      alternatives: ["Seated leg curl", "lying leg curl", "slider leg curl als machine ontbreekt"],
      cue: "Buig in twee, laat in drie terug.",
    }),
    "bulgarian-split-squat-smith": detail({
      purpose: "Unilaterale beenkracht, heupcontrole en links-rechtsbelastbaarheid ontwikkelen.",
      muscles: ["Quadriceps en gluteus maximus primair", "adductoren", "hamstrings", "heup- en enkelstabilisatoren"],
      why: "De Smith-machine geeft stabiliteit en beperkt grip, zodat de benen serieus belast kunnen worden zonder dat ellebogen de limiterende factor zijn.",
      setup: ["Achterste voet op een lage bank.", "Voorste voet voldoende ver naar voren.", "Meeste gewicht op het voorste been.", "Korte pas benadrukt quadriceps; langere pas benadrukt bilspier."],
      execution: ["Zak vooral recht omlaag.", "Houd de voorste voet volledig op de vloer.", "Laat de knie natuurlijk naar voren bewegen in lijn met de tenen.", "Duw via de voorste voet omhoog."],
      posture: ["Bekken blijft recht.", "Knie volgt tweede/derde teen.", "Romp stabiel.", "Achterste been helpt minimaal."],
      feel: "Bovenbeen en bil van het voorste been; geen scherpe diepe heuppijn.",
      mistakes: ["Afzetten met achterste been.", "Voorste hiel optillen.", "Bekken opendraaien.", "Knie naar binnen.", "Te hoge bank."],
      progression: ["2–3 × 6–10 per been.", "Eerst reps opbouwen, daarna een kleine Smith-stap.", "Unilateraal liever conservatieve gewichtsverhogingen."],
      regression: ["Lagere bank.", "Minder diepte.", "Gewone split squat met steun.", "Slechts 2 sets."],
      alternatives: ["Smith split squat zonder verhoogde achtervoet", "supported reverse lunge"],
      cue: "Zak recht omlaag; voorste voet doet het werk.",
    }),
    "seated-calf-raise": detail({
      purpose: "Soleus- en kuitbelastbaarheid zwaar opbouwen, inclusief een gecontroleerde isometrische eindhold.",
      muscles: ["Soleus primair", "gastrocnemius secundair", "Achillespees", "voet- en enkelstabilisatoren"],
      why: "De soleus levert veel werk tijdens hardlopen. Zware dynamische kuitkracht plus een hold bouwt meer praktische belastbaarheid dan alleen eindeloze lichte reps.",
      setup: ["Voorvoet stabiel op het platform.", "Kniepad stevig maar comfortabel.", "Hielen vrij om te zakken."],
      execution: ["Zak gecontroleerd en pauzeer kort onderin.", "Kom volledig op de voorvoet.", "Houd bovenin één seconde.", "Zak in 2–3 seconden.", "Na de laatste rep 15–25 sec hoog/midden vasthouden."],
      posture: ["Enkels bewegen recht.", "Niet over de kleine tenen naar buiten rollen.", "Hold mag niet langzaam inzakken."],
      feel: "Diepe kuitspanning en rek onderin; geen scherpe Achilles- of enkelpijn.",
      mistakes: ["Stuiteren.", "Korte halve reps.", "Naar buiten rollen.", "Hold laten zakken.", "Te snel gewicht verhogen."],
      progression: ["Wanneer 3 × 12 plus hold volledig beheerst is: gewicht verhogen.", "Na verhoging terug naar 8–10 reps en kortere hold."],
      regression: ["Lichter gewicht.", "Minder diepe rek.", "Kortere hold."],
      alternatives: ["Bent-knee calf raise aan leg press", "zittende dumbbell calf raise"],
      cue: "Volledig omhoog, langzaam omlaag, hold blijft hoog.",
    }),
    "weighted-dead-bug": detail({
      purpose: "Rompstijfheid en bekkencontrole trainen terwijl armen en benen bewegen.",
      muscles: ["Diepe buikspieren", "rectus abdominis", "obliques", "heupflexoren gecontroleerd"],
      why: "Helpt ribben en bekken gecontroleerd houden bij krachttraining en hardlopen zonder zware rugbelasting.",
      setup: ["Rug op de vloer.", "Heupen en knieën ongeveer 90°.", "Lichte dumbbell boven borst of handen tegen een bal."],
      execution: ["Breng ribben licht omlaag.", "Strek langzaam één been en eventueel tegenovergestelde arm.", "Stop vóór de onderrug loskomt.", "Adem uit tijdens uitstrekken en kom rustig terug."],
      posture: ["Onderug rustig tegen de vloer, niet maximaal persen.", "Nek ontspannen.", "Bekken blijft stil."],
      feel: "Buikspanning; niet trekken in onderrug of knijpen voorin de heup.",
      mistakes: ["Been te laag waardoor rug loskomt.", "Adem vasthouden.", "Snel bewegen.", "Te zwaar gewicht boven de borst."],
      progression: ["2–3 × 6–8 per kant.", "Strek het been geleidelijk lager of voeg een lichte dumbbell toe; snelheid blijft traag."],
      regression: ["Alleen hiel aantikken.", "Alleen benen of alleen armen bewegen.", "Geen extra gewicht."],
      alternatives: ["Dead bug zonder gewicht", "ball press dead bug"],
      cue: "Stop vóór je onderrug loskomt.",
    }),
    "cable-external-rotation-dynamic": detail({
      purpose: "Rotator-cuffkracht door een gecontroleerde concentrische en excentrische beweging opbouwen.",
      muscles: ["Infraspinatus", "teres minor", "achterste deltoideus secundair", "rotator-cuffpees"],
      why: "Dynamische belasting vult de isometrische holds aan en bereidt de schouder voor op normale armbeweging en later overheadwerk.",
      setup: ["Kabel op ellebooghoogte.", "Zij naar station.", "Elleboog 90° naast romp.", "Handdoek of polsmanchet gebruiken als dat controle/grip verbetert."],
      execution: ["Draai in 2 seconden naar buiten.", "Stop vóór schouder of romp gaat compenseren.", "Laat in 3 seconden terugtrekken.", "Laat de stapel niet neerkomen."],
      posture: ["Bovenarm rustig.", "Pols neutraal.", "Schouder laag zonder hard omlaag te trekken.", "Ribben boven bekken."],
      feel: "Achter- en zijkant schouder; geen scherpe voorzijdepijn.",
      mistakes: ["Romp meedraaien.", "Elleboog los van romp.", "Kabel terug laten schieten.", "Shruggen.", "Te grote range."],
      progression: ["3 × 8–15.", "Na 3 × 15 perfect en rustige volgende ochtend: kabel één stap verhogen.", "Absolute gewichten blijven kleiner door de lange hefboom; dat is normaal."],
      regression: ["Kabel lichter.", "Kleinere range.", "Terug naar isometrische hold."],
      alternatives: ["Band external rotation", "side-lying dumbbell external rotation als elleboog het verdraagt"],
      cue: "Twee tellen uit, drie tellen terug.",
    }),
    "serratus-wall-slide": detail({
      purpose: "Serratusfunctie en gecontroleerde opwaartse schouderbladrotatie trainen.",
      muscles: ["Serratus anterior primair", "onderste/bovenste trapezius", "rotator cuff", "core stabiliserend"],
      why: "De oefening leert armheffen zonder schouderbladen geforceerd vast te zetten en ondersteunt later duw- en overheadbewegingen.",
      setup: ["Foamroller horizontaal tegen muur.", "Onderarmen op roller.", "Lichte miniband om polsen indien verdraagbaar.", "Halve stap van de muur."],
      execution: ["Duw onderarmen licht in de roller.", "Duw polsen zacht uit elkaar tegen de band.", "Rol langzaam omhoog.", "Laat schouderbladen rond de ribbenkast opwaarts bewegen en keer rustig terug."],
      posture: ["Ribben boven bekken.", "Geen holle onderrug.", "Schouders niet krampachtig naar achteren/omlaag trekken."],
      feel: "Activiteit langs de zijribben en gecontroleerde beweging rond schouderbladen.",
      mistakes: ["Ribben naar voren steken.", "Te zware band.", "Onderarmen van roller halen.", "Schouderbladen vastknijpen."],
      progression: ["3 × 8–12.", "Eerst reps, daarna iets meer bandspanning of grotere gecontroleerde hoogte."],
      regression: ["Zonder band.", "Zonder foamroller als simpele wall slide.", "Kleinere hoogte."],
      alternatives: ["Forearm wall slide", "scapular push-up plus"],
      cue: "Ribben stil; schouderblad mag omhoog draaien.",
    }),
    "incline-pushup-plus": detail({
      purpose: "Duwkracht en serratusbelasting opbouwen in een schaalbare gesloten-ketenbeweging.",
      muscles: ["Borstspieren", "triceps", "voorste deltoideus", "serratus anterior", "core"],
      why: "De incline maakt de belasting doseerbaar. De plus traint schouderbladprotractie en vormt een belangrijk criterium voor terugkeer naar overhead press.",
      setup: ["Handen iets breder dan schouders op bank of stang.", "Handen eventueel enkele graden naar buiten.", "Lichaam in één rechte lijn."],
      execution: ["Laat borst gecontroleerd zakken.", "Ellebogen ongeveer 30–60° van de romp.", "Duw omhoog.", "Duw bovenin nog iets verder van de ondergrond zonder de rug overdreven bol te maken."],
      posture: ["Schouderbladen bewegen natuurlijk naar elkaar bij zakken en uit elkaar bij de plus.", "Schouders weg van oren zonder hard omlaag te trekken.", "Ribben en bekken blijven gestapeld."],
      feel: "Borst, triceps en zijribben/serratus; maximaal lichte stabiele schoudergevoeligheid.",
      mistakes: ["Ellebogen recht zijwaarts.", "Heupen doorzakken.", "Schouderbladen vastzetten.", "Plus maken via extreme bovenrugbol.", "Elke rep pijnlijker laten worden."],
      progression: ["3 × 8–15 op RIR 2–3.", "Van hoge naar lagere verhoging, daarna vloer, gewichtsvest/rugzak of band.", "Maak pas moeilijker bij 3 × 15 met goede controle."],
      regression: ["Hogere bank of muur.", "Kleinere diepte.", "Plus apart uitvoeren."],
      alternatives: ["Machine chest press met comfortabele greep", "wall push-up plus"],
      phaseDifferences: ["Week 1–2: comfortabele hoogte, RIR 3–4.", "Week 3–5: lagere incline mogelijk bij maximaal 2/10 en rustige volgende ochtend.", "Week 6–8: RIR 2–3; niet automatisch naar vloer als techniek verslechtert."],
      cue: "Zak als plank; duw bovenin de bank weg.",
    }),
    "cable-scaption-cuffs": detail({
      purpose: "Armheffen in het scapulaire vlak versterken met minimale gripbelasting.",
      muscles: ["Middelste/voorste deltoideus", "supraspinatus en overige rotator cuff", "serratus/trapezius voor schouderbladbeweging"],
      why: "Scaption sluit aan bij normale schouderfunctie. Cuffs ontzien de golferselleboog en lange hefboom geeft voldoende prikkel met weinig absoluut gewicht.",
      setup: ["Kabels laag.", "Polsmanchetten gebruiken.", "Armen 20–30° vóór de zijlijn.", "Duimen omhoog of schuin omhoog."],
      execution: ["Hef gecontroleerd tot schouderhoogte of eerder.", "Pauzeer kort zonder shrug.", "Laat in 3 seconden zakken."],
      posture: ["Ribben boven bekken.", "Geen momentum uit benen.", "Hand niet lager laten hangen dan elleboog.", "Schouderblad mag bewegen."],
      feel: "Zijkant schouder en stabiele cuffactiviteit; geen knijpende voorzijdepijn.",
      mistakes: ["Intern roteren alsof je een kan leeggiet.", "Boven schouderhoogte forceren.", "Shruggen.", "Rug hol trekken.", "Te zwaar kabelgewicht."],
      progression: ["3 × 10–15.", "Eerst 15 technisch nette reps; daarna één kleine kabelstap en terug naar 10."],
      regression: ["Kleinere hoogte.", "Eén arm tegelijk.", "Lichtere kabel of geen cuffspanning."],
      alternatives: ["Dumbbell scaption met zeer losse greep", "landmine press alleen via het terugkeerpad"],
      cue: "Duimen omhoog; hef vóór je zijlijn.",
    }),
    "rear-delt-fly-machine": detail({
      purpose: "Achterste schouder en schouderbladcontrole versterken met rompsteun.",
      muscles: ["Achterste deltoideus primair", "rhomboidei en middelste trapezius secundair", "rotator cuff stabiliserend"],
      why: "Borststeun beperkt compensatie uit onderrug. Een neutrale/losse greep of cuffs kan elleboog- en gripbelasting verminderen.",
      setup: ["Zitting zo dat handgrepen op schouderhoogte zijn.", "Borst tegen steun.", "Neutrale greep indien mogelijk.", "Elleboog licht gebogen."],
      execution: ["Beweeg armen naar buiten en licht naar achteren.", "Stop als bovenarmen ongeveer in lijn met romp zijn.", "Keer langzaam terug."],
      posture: ["Borst blijft op steun.", "Schouders niet optrekken.", "Schouderbladen niet maximaal samenknijpen.", "Polsen neutraal."],
      feel: "Achterkant schouders en lichte bovenrugactiviteit; geen brachialis- of binnenelleboogpijn.",
      mistakes: ["Te ver naar achteren trekken.", "Momentum.", "Hard knijpen.", "Schouders naar oren.", "Gewicht terug laten vallen."],
      progression: ["2–3 × 10–15.", "Eerst reps en tempo; daarna een kleine machinestap."],
      regression: ["Losser grijpen, straps/cuffs, lagere weerstand of kortere range."],
      alternatives: ["Cable rear-delt fly met cuffs", "face pull met cuffs"],
      cue: "Beweeg vanuit de achterste schouder, niet uit een harde knijp.",
    }),
    "single-leg-leg-press": detail({
      purpose: "Zware unilaterale knie- en heupkracht ontwikkelen met hoge stabiliteit.",
      muscles: ["Quadriceps", "gluteus maximus", "adductoren", "heup- en kniestabilisatoren"],
      why: "Geeft de tweede serieuze beenprikkel en laat links/rechts gecontroleerd werken zonder gripbelasting.",
      setup: ["Eén voet ongeveer midden op platform.", "Bekken volledig tegen rugleuning.", "Andere voet blijft weg van het platform."],
      execution: ["Laat in controle zakken.", "Stop vóór bekken aan één kant optilt of onderrolt.", "Duw via de hele voet terug.", "Vermijd agressieve lock-out."],
      posture: ["Heupen recht.", "Knie volgt tenen.", "Volledige voetdruk.", "Rug tegen steun."],
      feel: "Bovenbeen en bil van het werkende been; geen scherpe voorste-heuppijn.",
      mistakes: ["Andere voet mee laten helpen.", "Bekken draaien.", "Knie naar binnen.", "Te diepe range.", "Hard op slot duwen."],
      progression: ["3 × 6–10 per been.", "Start RIR 3 en bouw naar RIR 2.", "Verhoog klein wanneer beide kanten 10 reps technisch halen."],
      regression: ["Lichter gewicht.", "Minder diepte.", "Bilaterale leg press als unilaterale bekkencontrole onvoldoende is."],
      alternatives: ["Supported split squat", "lage step-up"],
      cue: "Bekken stil, hele voet duwt.",
    }),
    "step-up": detail({
      purpose: "Functionele unilaterale heup- en knie-extensie voor trap-/loopachtige kracht.",
      muscles: ["Gluteus maximus", "quadriceps", "adductoren", "heupstabilisatoren", "kuit secundair"],
      why: "De oefening traint kracht over één been en kan zonder zware grip via Smith, vest of belt-constructie worden verzwaard.",
      setup: ["Box niet extreem hoog; bovenbeen ongeveer horizontaal of lager.", "Hele werkvoet op de box.", "Achterste voet licht op de vloer."],
      execution: ["Leun licht vanuit de heup voorover.", "Duw de box weg met het bovenste been.", "Breng bekken boven standbeen.", "Zak langzaam terug."],
      posture: ["Knie volgt tenen.", "Bekken blijft horizontaal.", "Romp blijft lang.", "Achterste been helpt minimaal."],
      feel: "Bil en bovenbeen van het been op de box; geen afzet in de achterste kuit.",
      mistakes: ["Hard afzetten met achterste voet.", "Alleen tenen op box.", "Knie naar binnen.", "Te hoge box.", "Ongecontroleerd afstappen."],
      progression: ["3 × 6–10 per been.", "Eerst hoogte/controle constant houden en reps opbouwen.", "Daarna Smith, gewichtsvest of belt squat-constructie."],
      regression: ["Lagere box.", "Steun vasthouden.", "Langzame step-down met hulp omhoog."],
      alternatives: ["Smith step-up", "supported reverse lunge"],
      cue: "Bovenste been doet het werk.",
    }),
    "standing-calf-raise": detail({
      purpose: "Zware kuit- en Achillesbelastbaarheid opbouwen met vrijwel gestrekte knie.",
      muscles: ["Gastrocnemius primair", "soleus", "Achillespees", "voet- en enkelstabilisatoren"],
      why: "Kuitkracht ondersteunt loopeconomie en enkelbelastbaarheid. Hier hoort serieuze dynamische weerstand bij, niet alleen lichte isometrie.",
      setup: ["Voorvoet stabiel op platform.", "Knieën vrijwel gestrekt maar niet hard op slot.", "Machinepad of Smith comfortabel geplaatst."],
      execution: ["Zak diep en gecontroleerd.", "Kom volledig omhoog.", "Verdeel druk over bal van grote én kleine teen.", "Laatste rep 20–30 sec vasthouden."],
      posture: ["Enkel beweegt recht.", "Geen knieflexie om gewicht te verplaatsen.", "Hold blijft hoog."],
      feel: "Oppervlakkige kuitspanning en gecontroleerde rek; geen scherpe Achilles- of enkelpijn.",
      mistakes: ["Naar buiten rollen.", "Stuiteren.", "Halve reps.", "Knieën hard locken.", "Hold laten instorten."],
      progression: ["3 × 6–10 plus 20–30 sec hold.", "Eerst 10 reps en volledige hold; daarna gewicht verhogen."],
      regression: ["Lichter gewicht.", "Minder diepe rek.", "Bilateraal met steun."],
      alternatives: ["Standing calf raise machine", "Smith calf raise", "leg-press calf raise"],
      cue: "Druk door grote én kleine teen.",
    }),
    "short-lever-copenhagen": detail({
      purpose: "Adductoren en laterale rompcontrole versterken met een korte, doseerbare hefboom.",
      muscles: ["Adductor longus/brevis/magnus", "gracilis", "obliques", "heupstabilisatoren"],
      why: "Adductoren helpen heup- en bekkencontrole tijdens hardlopen. De korte hefboom is een voorzichtige start omdat deze oefening forse spierpijn kan geven.",
      setup: ["Zijwaarts naast bank.", "Bovenste knie op bank.", "Steun op onderarm.", "Onderste been vrij."],
      execution: ["Til heupen op.", "Trek onderste been licht richting bovenste.", "Houd romp recht 15–30 sec.", "Wissel gecontroleerd."],
      posture: ["Schouder boven elleboog.", "Bekken niet naar achteren draaien.", "Romp in één lijn.", "Normaal ademen."],
      feel: "Binnenkant bovenbeen van het bovenste been en zijkant romp; geen scherpe liespijn.",
      mistakes: ["Te lange hefboom starten.", "Heupen laten zakken.", "Bekken openen.", "Adem vasthouden.", "Te veel sets bij eerste keer."],
      progression: ["2 × 15–30 sec per kant.", "Eerst holdduur; later pas langere hefboom of extra set."],
      regression: ["Kortere hold.", "Heupen minder hoog.", "Isometrische bal-/kussensqueeze."],
      alternatives: ["Side-lying adduction", "adductor squeeze"],
      cue: "Knie in de bank, heupen lang.",
    }),
    "iso-elbow-flexion-cuff": detail({
      purpose: "Elleboogbuigers isometrisch belasten zonder hard te hoeven grijpen.",
      muscles: ["Brachialis", "biceps brachii", "brachioradialis", "distale biceps-/brachialisregio"],
      why: "De cuff maakt het mogelijk te onderzoeken of elleboogflexie zelf verdraagbaar is terwijl de golferselleboog niet door grip wordt beperkt.",
      setup: ["Kabel laag.", "Cuff rond onderarm net boven pols.", "Bovenarm naast romp.", "Elleboog ongeveer 70–90° gebogen.", "Pols neutraal."],
      execution: ["Houd onderarm stil tegen trekkracht.", "Elleboog blijft naast romp.", "Adem door gedurende 25–40 sec."],
      posture: ["Schouder niet naar voren.", "Ribben boven bekken.", "Geen polsbuiging.", "Geen rompzwaai."],
      feel: "Stevige spanning in voorzijde bovenarm/elleboogflexoren; geen scherpe distale-biceps- of binnenelleboogpijn.",
      mistakes: ["Hard knijpen ondanks cuff.", "Schouder naar voren trekken.", "Hoek langzaam verliezen.", "Maximaal persen.", "Adem vasthouden."],
      progression: ["Begin 5–6/10 en bouw naar 3 × 40 sec.", "Verhoog daarna kabel.", "Vanaf week 4 wisselen tussen ongeveer 60° en 100° omdat isometrische kracht hoekspecifiek is."],
      regression: ["Lichtere kabel.", "Kortere hold.", "Comfortabelere hoek.", "Bovenarm extra ondersteunen."],
      alternatives: ["Isometrische elbow-flexion tegen band met cuff", "handmatige weerstand zonder grip"],
      phaseDifferences: ["Week 1–2: 70–90°, 25–30 sec, 5–6/10.", "Week 3–5: 30–40 sec, 6–7/10 en eventueel tweede hoek.", "Week 6–8: tot 7–8/10, zonder vormverlies."],
      cue: "Elleboog blijft naast je romp; cuff doet het trekwerk.",
    }),
    "slow-cable-elbow-flexion-cuff": detail({
      purpose: "Brachialis en overige elleboogbuigers dynamisch concentrisch én excentrisch versterken.",
      muscles: ["Brachialis primair", "biceps brachii", "brachioradialis", "distale elleboogflexorstructuren"],
      why: "De cuff scheidt elleboogflexie van zware grip. Dit is de brug naar neutrale kabelgreep, rope hammer curl en later normale curls/trekbewegingen.",
      setup: ["Cuff rond onderarm.", "Kabel laag.", "Bovenarm naast romp.", "Start bijna gestrekt maar niet vergrendeld."],
      execution: ["Buig in 2 seconden tot ongeveer 100–110°.", "Houd één seconde.", "Laat in 3 seconden terugzakken.", "Bovenarm blijft stil."],
      posture: ["Pols neutraal.", "Schouder niet naar voren.", "Geen rompzwaai.", "Normaal ademen."],
      feel: "Geleidelijke spierbelasting in de voorzijde bovenarm; geen scherpe pijn bij de elleboogplooi.",
      mistakes: ["Bovenarm naar voren.", "Te ver doorcurlen.", "Kabel terug laten trekken.", "Grip onnodig aanspannen.", "Volledige lock-out forceren."],
      progression: ["3 × 8–12 met 2-1-3-tempo.", "Cuff → losse neutrale kabelgreep → rope hammer curl → dumbbell hammer curl → later gewone curls/trekken.", "Ga alleen een stap verder bij stabiele volgende ochtend."],
      regression: ["Kleinere range.", "Lichter gewicht.", "Alleen isometrische variant.", "Langzamere maar kortere beweging."],
      alternatives: ["Rope hammer curl met losse greep zodra toegestaan", "band curl met cuff"],
      phaseDifferences: ["Week 1–2: cuff en RIR 3–4.", "Week 3–5: RIR 2–3 en cuff zwaarder.", "Week 6–8: eventueel neutrale losse grip, meestal RIR 2; geen maximale gewone curls."],
      cue: "Bovenarm stil; drie tellen terug.",
    }),
    "weighted-wrist-flexion": detail({
      purpose: "Polsflexoren en de gemeenschappelijke flexorpees dynamisch en progressief belasten.",
      muscles: ["Pols- en vingerflexoren", "pronator teres secundair", "mediale elleboogpeesaanhechting"],
      why: "Volledig herstel vraagt naast holds ook concentrische en vooral gecontroleerde excentrische belasting.",
      setup: ["Onderarm volledig ondersteund.", "Handpalm omhoog.", "Pols net over rand.", "Dumbbell stevig maar niet krampachtig."],
      execution: ["Krul in 2 seconden omhoog.", "Onderarm blijft stil.", "Laat in 3–4 seconden zakken door een comfortabele volledige range."],
      posture: ["Schouder ontspannen.", "Elleboog blijft ondersteund.", "Geen vinger-openrol tenzij bewust en pijnvrij."],
      feel: "Werk in onderarmflexoren; lichte stabiele peesgevoeligheid kan, stekende botpijn niet.",
      mistakes: ["Snel laten vallen.", "Onderarm optillen.", "Hard knijpen.", "Maximaal in flexie persen.", "Pijn na iedere rep laten toenemen."],
      progression: ["Bij 3 × 15 met maximaal 2/10 en rustige volgende ochtend: 0,5–1 kg verhogen.", "Ga terug naar 8–10 reps en bouw weer op."],
      regression: ["Lichter gewicht.", "Kleinere range.", "Terug naar isometrische polsflexie."],
      alternatives: ["Cable wrist flexion", "band wrist flexion"],
      cue: "Twee omhoog, vier rustig omlaag.",
    }),
    "pronation-supination-lever": detail({
      purpose: "Onderarmrotatie en belastbaarheid van pronator-/supinatorstructuren opbouwen.",
      muscles: ["Pronator teres/quadratus", "supinator", "biceps secundair", "pols- en elleboogstabilisatoren"],
      why: "Pronatie kan bij golferselleboog gevoelig zijn. Een verstelbare hefboom maakt zeer kleine, controleerbare belastingsstappen mogelijk.",
      setup: ["Elleboog 90° en bovenarm naast romp.", "Onderarm ondersteund.", "Pak uiteinde van lichte dumbbell/hamer/stang.", "Start met korte hefboom."],
      execution: ["Draai in ongeveer 3 seconden van handpalm omhoog naar omlaag.", "Beweeg alleen vanuit onderarm.", "Keer even langzaam terug."],
      posture: ["Pols blijft neutraal.", "Elleboog en schouder stil.", "Geen knijpende maximale grip."],
      feel: "Gelijkmatige spanning rond onderarm; geen scherpe mediale elleboogpijn.",
      mistakes: ["Te lange hefboom starten.", "Pols buigen.", "Elleboog van steun tillen.", "Snel door eindstand vallen.", "Gewicht onderschatten."],
      progression: ["2–3 × 8–12 per richting.", "Maak zwaarder met iets meer gewicht, langere hefboom of langzamer tempo — slechts één variabele tegelijk."],
      regression: ["Kortere hefboom.", "Minder gewicht.", "Kleinere rotatiehoek."],
      alternatives: ["Hammer pronation/supination", "kabelrotatie met lichte greep"],
      cue: "Elleboog stil; de hefboom beweegt langzaam.",
    }),
    "face-pull": detail({
      purpose: "Achterste schouder, bovenrug en schoudercontrole trainen met aanpasbare grip.",
      muscles: ["Achterste deltoideus", "middelste/onderste trapezius", "rhomboidei", "rotator cuff"],
      why: "Geeft de derde schouderprikkel en kan via cuffs worden uitgevoerd als rope-grip de golferselleboog irriteert.",
      setup: ["Kabel op oog-/voorhoofdhoogte.", "Rope los vastpakken of cuffs rond polsen/onderarmen.", "Sta stabiel zonder achterover te hangen."],
      execution: ["Trek richting voorhoofd.", "Laat ellebogen niet extreem hoog uitwaaieren.", "Eindig met handen naast gezicht.", "Laat gecontroleerd terugkomen."],
      posture: ["Ribben boven bekken.", "Schouders niet optrekken.", "Geen achteroverleunende row.", "Polsen neutraal."],
      feel: "Achterste schouders en bovenrug; geen trekkende brachialis- of binnenelleboogpijn.",
      mistakes: ["Momentum.", "Achterover leunen.", "Te hard knijpen.", "Ellebogen extreem hoog.", "Rope naar borst trekken."],
      progression: ["2–3 × 10–15.", "Eerst reps/tempo; daarna kleine kabelstap.", "Grip pas zwaarder maken als elleboog stabiel blijft."],
      regression: ["Cuffs gebruiken.", "Lichtere kabel.", "Kortere range."],
      alternatives: ["Rear-delt flymachine", "cable rear-delt fly met cuffs"],
      cue: "Trek naar je voorhoofd zonder achterover te leunen.",
    }),
    "half-kneeling-landmine-press": detail({
      purpose: "Gecontroleerde eerste terugkeer naar een schuine overheadachtige drukbeweging.",
      muscles: ["Voorste deltoideus", "bovenste borst", "triceps", "serratus anterior", "rotator cuff", "core/bil voor stabiliteit"],
      why: "De schuine baan is vaak beter doseerbaar dan volledig verticaal drukken en laat het schouderblad natuurlijk meebewegen.",
      setup: ["Kniel met de knie aan dezelfde kant als de drukkende arm op de vloer.", "Andere voet voor.", "Pak stangeinde met neutrale greep.", "Start bij schouderhoogte."],
      execution: ["Span bil van de knielende zijde.", "Druk stang schuin omhoog en naar voren.", "Laat schouderblad meebewegen.", "Laat gecontroleerd terugzakken."],
      posture: ["Ribben boven bekken.", "Geen holle rug.", "Schouder niet naar voren uit positie laten glijden.", "Pols in lijn met onderarm."],
      feel: "Gecontroleerde spanning in schouder, borst en serratus; geen toenemende voorzijdepijn.",
      mistakes: ["Ribben omhoog.", "Onderrug hol.", "Schouderblad vastzetten.", "Te zwaar starten.", "Iedere rep pijnlijker laten worden."],
      progression: ["Start 2–3 × 8–12 op RIR 3–4.", "Eerst twee probleemloze weken opbouwen voordat machine overhead press wordt getest."],
      regression: ["Lichtere stangbelasting.", "Staande two-hand landmine press.", "Kleinere range.", "Terug naar incline push-up plus."],
      alternatives: ["Two-hand landmine press", "hoge incline push-up plus"],
      phaseDifferences: ["Week 1–2: niet uitvoeren.", "Week 3–5: alleen beschikbaar na afvinken van alle voorwaarden.", "Week 6–8: verder opbouwen als reactie stabiel blijft; geen maximale belasting."],
      cue: "Bil aan, ribben stil, schuin vooruit drukken.",
    }),
    "machine-overhead-press-neutral": detail({
      purpose: "Verticale drukcapaciteit gecontroleerd terugbrengen na een stabiele landminefase.",
      muscles: ["Deltoideus", "triceps", "bovenste borst", "serratus/trapezius", "rotator cuff"],
      why: "De machine geeft stabiliteit en een neutrale greep, zodat de schouderbelasting zorgvuldig kan worden opgebouwd zonder vrije haltercontrole of zware grip.",
      setup: ["Alleen na twee probleemloze weken landmine press.", "Handgrepen tussen kin- en oorhoogte, niet diep onder schouder.", "Rugsteun licht schuin.", "Neutrale/semi-neutrale greep.", "Ellebogen iets vóór romp."],
      execution: ["Span buik en billen licht.", "Druk omhoog zonder ribben op te tillen.", "Laat schouderbladen natuurlijk opwaarts draaien.", "Stop eventueel vóór lock-out.", "Laat in 2–3 seconden zakken."],
      posture: ["Geen holle onderrug.", "Schouderbladen niet hard omlaag trekken.", "Polsen boven ellebogen.", "Romp blijft tegen steun."],
      feel: "Gelijkmatige schouder- en tricepsbelasting; geen toenemende voorzijdepijn of instabiliteit.",
      mistakes: ["Te lage startpositie.", "Ellebogen exact zijwaarts.", "Borst extreem optillen.", "Schouderbladen vastknijpen.", "Gewicht verhogen terwijl bovenste range instabiel is."],
      progression: ["Start 2 × 10–12 op RIR 4 en maximaal 2/10 pijn.", "Later 3 × 8–12 op RIR 2–3.", "Niet op dezelfde dag als meerdere nieuwe zware schouderprikkels."],
      regression: ["Lichter gewicht.", "Kortere range.", "Eén stap terug naar landmine press.", "Hogere incline push-up plus."],
      alternatives: ["Half-kneeling landmine press", "machine incline press met neutrale greep"],
      phaseDifferences: ["Week 1–5: niet uitvoeren.", "Week 6–8: alleen testen na twee probleemloze landmineweken en alle criteria.", "Na week 8: verdere progressie hoort in een nieuw vervolgplan."],
      cue: "Ribben laag; schouderblad mag omhoog.",
    }),
  };

  function mobilityDetail(config) {
    return detail({
      ...config,
      why:
        `${config.why} Mobiliteit vergroot of onderhoudt bewegingsruimte, maar vervangt de progressieve krachtoefeningen niet.`,
      phaseDifferences: [
        "Week 1–2: rustig bereik verkennen, nooit forceren.",
        "Week 3–5: iets vloeiender of langer als de volgende ochtend rustig blijft.",
        "Week 6–8: bewegingskwaliteit onderhouden naast de zwaardere krachttraining.",
      ],
    });
  }

  Object.assign(EXERCISE_DETAILS, {
    "half-kneeling-hip-flexor-stretch": mobilityDetail({
      purpose: "Comfortabele heupextensieruimte en bekkencontrole oefenen.",
      muscles: ["Iliopsoas", "rectus femoris", "voorste heupstructuren"],
      why: "Kan spanning voorin heup/bovenbeen verminderen zonder te stellen dat 'korte heupflexoren' automatisch de oorzaak zijn.",
      setup: ["Eén knie op zachte ondergrond, andere voet voor.", "Achterste bil aanspannen."],
      execution: ["Kantel bekken achterover.", "Beweeg slechts een klein stukje naar voren.", "Houd 30–45 sec per kant."],
      posture: ["Romp recht.", "Onderrug niet hol.", "Voorste knie stabiel."],
      feel: "Rek voorzijde heup/bovenbeen, niet diep scherp in de lies.",
      mistakes: ["Ver naar voren leunen.", "Onderrug hol trekken.", "Bil ontspannen."],
      progression: ["2 × 30–45 sec; vergroot eerst controle en pas daarna lichte voorwaartse verplaatsing."],
      regression: ["Kortere hold of knie verder naar achteren/voorvoet dichterbij voor minder rek."],
      alternatives: ["Staande hip-flexor stretch met achterste bil aangespannen."],
      cue: "Bil aan, riemgesp omhoog.",
    }),
    "couch-stretch": mobilityDetail({
      purpose: "Voorzijde bovenbeen en heup gecontroleerd verlengen.",
      muscles: ["Rectus femoris", "overige quadriceps", "heupflexoren"],
      why: "Vult heup- en beenkracht aan door beschikbare heupextensie/knieflexie rustig te oefenen.",
      setup: ["Achterste knie bij muur of bank, voet omhoog.", "Voorste voet voor.", "Begin met ruime afstand tot de muur."],
      execution: ["Span achterste bil.", "Breng romp geleidelijk rechterop.", "Houd 30–45 sec per kant."],
      posture: ["Bekken licht achterover.", "Geen holle rug.", "Niet in kniepijn hangen."],
      feel: "Rek voorzijde bovenbeen/heup, geen scherpe kniedruk.",
      mistakes: ["Knie direct tegen muur plaatsen.", "Rug hol trekken.", "Te snel rechtop komen."],
      progression: ["2 × 30–45 sec; verklein de afstand tot muur geleidelijk."],
      regression: ["Knie verder van muur of gewone half-kneeling stretch."],
      alternatives: ["Staande quadricepsstretch met bekkencontrole."],
      cue: "Begin verder van de muur dan je denkt.",
    }),
    "90-90-hip-switches": mobilityDetail({
      purpose: "Interne en externe heuprotatie actief en gecontroleerd bewegen.",
      muscles: ["Diepe heuprotatoren", "bilspieren", "adductoren"],
      why: "Onderhoudt rotatiecapaciteit die nuttig is voor heupcontrole, zonder passief in eindstand te duwen.",
      setup: ["Zit met beide knieën gebogen en voeten op de vloer.", "Handen eventueel achter je voor steun."],
      execution: ["Laat beide knieën langzaam naar één kant zakken.", "Keer via het midden terug.", "Doe 2 × 6–10 per kant."],
      posture: ["Zitbotten zo veel mogelijk op de vloer.", "Romp lang.", "Geen snelheid gebruiken."],
      feel: "Rustige spanning rond buiten- en binnenzijde heup, geen knelling diep voorin.",
      mistakes: ["Knieën laten vallen.", "Eindstand forceren.", "Bekken volledig optillen."],
      progression: ["Minder handsteun of iets vloeiender bewegen."],
      regression: ["Kleinere uitslag of één zijde tegelijk."],
      alternatives: ["Seated hip internal-rotation rocks."],
      cue: "Langzaam wisselen; zitbotten zwaar.",
    }),
    "adductor-rock-back": mobilityDetail({
      purpose: "Adductoren dynamisch door een comfortabele lengtestand bewegen.",
      muscles: ["Adductoren", "mediale hamstrings", "heupkapsel secundair"],
      why: "Sluit aan bij Copenhagen- en unilaterale beenkracht door bewegingsruimte rond de binnenzijde van het bovenbeen te onderhouden.",
      setup: ["Start op handen en knieën.", "Strek één been zijwaarts met voet of hak op vloer."],
      execution: ["Duw heupen langzaam naar achteren.", "Pauzeer kort.", "Kom terug voor 2 × 8–12 per kant."],
      posture: ["Rug neutraal.", "Bekken blijft recht.", "Geen draai naar het gestrekte been."],
      feel: "Rek binnenzijde bovenbeen, geen scherpe liespijn.",
      mistakes: ["Rug rond maken.", "Te ver achteruit duwen.", "Voetpositie forceren."],
      progression: ["Iets grotere rustige range of korte pauze achterin."],
      regression: ["Knie licht buigen of minder ver zijwaarts plaatsen."],
      alternatives: ["Wide-knee rock-back."],
      cue: "Heupen terug, rug lang.",
    }),
    "dynamic-hamstring-mobility": mobilityDetail({
      purpose: "Hamstrings dynamisch door heupbuiging bewegen zonder lang passief trekken.",
      muscles: ["Hamstrings", "kuit secundair", "achterste keten"],
      why: "Vult leg curls en hardloopkracht aan door een gecontroleerde heupscharnier te oefenen.",
      setup: ["Eén hak voor je.", "Knie licht gebogen.", "Standbeen stabiel."],
      execution: ["Duw heupen naar achteren met lange rug.", "Houd 1–2 sec.", "Kom terug voor 2 × 8 per kant."],
      posture: ["Rug lang.", "Bekken recht.", "Niet aan tenen trekken."],
      feel: "Milde rek achterkant bovenbeen, geen zenuwachtige scherpe trekkracht.",
      mistakes: ["Rug bol.", "Veren.", "Knie hard op slot.", "Tenen agressief aantrekken."],
      progression: ["Iets dieper vanuit de heup, niet sneller."],
      regression: ["Meer kniebuiging of minder heupscharnier."],
      alternatives: ["Supine active hamstring extension."],
      cue: "Heupen terug, rug blijft lang.",
    }),
    "calf-stretch-straight-knee": mobilityDetail({
      purpose: "Kuit en enkel met gestrekte knie rustig door dorsiflexie bewegen.",
      muscles: ["Gastrocnemius", "Achillespees", "enkelstructuren"],
      why: "Ondersteunt de bewegingsruimte die nodig is voor squats, calf raises en hardlopen.",
      setup: ["Achterste voet recht vooruit.", "Hiel op de grond.", "Knie gestrekt maar niet geforceerd."],
      execution: ["Leun rustig naar voren.", "Houd 2 × 30 sec per kant."],
      posture: ["Voetboog blijft actief.", "Niet naar buiten rollen.", "Bekken naar voren gericht."],
      feel: "Rek hoog/midden in kuit, geen scherpe Achilles- of enkelpijn.",
      mistakes: ["Hiel optillen.", "Voet uitdraaien.", "In de voorste enkel knellen."],
      progression: ["Iets verder van de muur staan, hiel blijft laag."],
      regression: ["Kortere pas of kortere hold."],
      alternatives: ["Kuitstretch tegen leg-pressplatform zonder belasting."],
      cue: "Hiel zwaar, voet recht vooruit.",
    }),
    "calf-stretch-bent-knee": mobilityDetail({
      purpose: "Diepere kuitspier en enkelbeweging met gebogen knie oefenen.",
      muscles: ["Soleus", "Achillespees", "enkelstructuren"],
      why: "Sluit specifiek aan bij seated calf raise en de grote soleusbelasting tijdens hardlopen.",
      setup: ["Zelfde positie als gestrekte-kniestretch.", "Achterste knie licht buigen terwijl hiel blijft staan."],
      execution: ["Beweeg knie rustig naar voren.", "Houd 2 × 30 sec per kant."],
      posture: ["Hiel blijft laag.", "Knie volgt tenen.", "Voet rolt niet naar binnen of buiten."],
      feel: "Rek lager en dieper in de kuit, geen scherpe enkelknelling.",
      mistakes: ["Hiel optillen.", "Knie naar binnen.", "Te hard in eindstand duwen."],
      progression: ["Iets meer knieflexie bij stabiele hiel."],
      regression: ["Minder kniebuiging of kleinere voorwaartse verplaatsing."],
      alternatives: ["Soleus stretch met voorvoet op lichte verhoging."],
      cue: "Buig de knie, houd de hiel zwaar.",
    }),
    "open-book-rotation": mobilityDetail({
      purpose: "Bovenrugrotatie en ontspannen schouderbeweging onderhouden.",
      muscles: ["Thoracale rotatoren", "borstspieren licht", "schoudergordel"],
      why: "Kan bovenrugbeweging ondersteunen zonder te doen alsof een ronde bovenrug automatisch de oorzaak van schouderpijn is.",
      setup: ["Lig op zij, heupen en knieën gebogen.", "Armen voor je en knieën op elkaar."],
      execution: ["Draai bovenste arm en borstkas rustig open.", "Volg de hand met je ogen.", "Keer terug voor 2 × 6–8 per kant."],
      posture: ["Knieën blijven bij elkaar.", "Beweging komt uit bovenrug, niet uit een draaiend bekken.", "Adem uit bij openen."],
      feel: "Milde rotatie/rek in bovenrug en borst, geen scherpe schouderpijn.",
      mistakes: ["Knie optillen.", "Arm naar vloer forceren.", "Snel veren.", "Adem vasthouden."],
      progression: ["Langzamer uitademen en iets grotere comfortabele rotatie."],
      regression: ["Kussen onder bovenste arm of kleinere range."],
      alternatives: ["Seated thoracic rotation."],
      cue: "Knieën samen; ogen volgen je hand.",
    }),
  });

  const EXERCISE_META = {
    "warmup-bike-walk": { inputType: "none" },
    "bodyweight-squat": { inputType: "none" },
    "glute-bridge": { inputType: "none" },
    "scapular-push-up": { inputType: "none" },
    "hip-circles": { inputType: "none" },
    "arm-circles": { inputType: "none" },
    "wall-slide-unweighted": { inputType: "none" },
    "warmup-set-first-exercise": { inputType: "none" },
    "iso-cable-external-rotation": { inputType: "weight-seconds", weightRange: { min: 0, max: 40, step: 0.5 }, secondsRange: { min: 15, max: 60, step: 5 }, protocol: { rest: "±30 sec tijdens armwissel", tempo: "statische hold", intensity: "week 1–2: 5–6/10; later 7–8/10" } },
    "iso-wrist-flexion": { inputType: "weight-seconds", weightRange: { min: 0, max: 30, step: 0.5 }, secondsRange: { min: 15, max: 60, step: 5 }, protocol: { rest: "30–45 sec", tempo: "statische hold", intensity: "stevig, nooit maximaal" } },
    "hack-squat-or-leg-press": { choices: ["Hack squat", "Leg press"], weightRange: { min: 0, max: 350, step: 2.5 }, repRange: { min: 1, max: 15 }, protocol: { rest: "2 min", tempo: "2–3 sec zakken", intensity: "RIR 2–3; niet tot falen" } },
    "hip-thrust-machine": { weightRange: { min: 0, max: 300, step: 2.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "90 sec", tempo: "1 sec vasthouden bovenin; gecontroleerd zakken", intensity: "RIR 2" } },
    "leg-curl": { weightRange: { min: 0, max: 160, step: 1 }, repRange: { min: 1, max: 20 }, protocol: { rest: "75–90 sec op Dag 1; 60 sec op Dag 3", tempo: "2 sec buigen, 1 sec knijpen, 3 sec terug", intensity: "RIR 2–3" } },
    "bulgarian-split-squat-smith": { weightRange: { min: 0, max: 180, step: 2.5 }, repRange: { min: 1, max: 15 }, protocol: { rest: "60–90 sec na beide benen", tempo: "gecontroleerd zakken en opstaan", intensity: "1–3 reps over" } },
    "seated-calf-raise": { weightRange: { min: 0, max: 180, step: 2.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "60 sec", tempo: "1 sec boven, 2–3 sec zakken", intensity: "laatste rep 15–25 sec hold" } },
    "weighted-dead-bug": { weightRange: { min: 0, max: 30, step: 0.5 }, repRange: { min: 1, max: 15 }, protocol: { rest: "30 sec", tempo: "langzaam uitstrekken en uitademen", intensity: "stop vóór onderrug loskomt" } },
    "cable-external-rotation-dynamic": { weightRange: { min: 0, max: 40, step: 0.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "30–45 sec tijdens armwissel", tempo: "2 sec uit, 3 sec terug", intensity: "faseafhankelijk RIR 3–4 naar RIR 2" } },
    "serratus-wall-slide": { inputType: "reps-only", repRange: { min: 1, max: 20 }, protocol: { rest: "45 sec", tempo: "langzaam omhoog en terug", intensity: "controle vóór bandspanning" } },
    "incline-pushup-plus": { inputType: "reps-only", repRange: { min: 1, max: 25 }, protocol: { rest: "60–75 sec", tempo: "gecontroleerd", intensity: "RIR 2–3" } },
    "cable-scaption-cuffs": { weightRange: { min: 0, max: 40, step: 0.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "45–60 sec", tempo: "3 sec zakken", intensity: "technisch zwaar binnen comfortabele hoogte" } },
    "rear-delt-fly-machine": { weightRange: { min: 0, max: 100, step: 0.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "60 sec", tempo: "rustig uit en langzaam terug", intensity: "geen momentum" } },
    "single-leg-leg-press": { weightRange: { min: 0, max: 220, step: 2.5 }, repRange: { min: 1, max: 15 }, protocol: { rest: "60–75 sec na beide benen", tempo: "gecontroleerd zakken", intensity: "start RIR 3; bouw naar RIR 2" } },
    "step-up": { weightRange: { min: 0, max: 160, step: 1 }, repRange: { min: 1, max: 15 }, protocol: { rest: "60 sec", tempo: "gecontroleerd omhoog en langzaam terug", intensity: "werkbeen blijft leidend" } },
    "standing-calf-raise": { weightRange: { min: 0, max: 250, step: 2.5 }, repRange: { min: 1, max: 15 }, protocol: { rest: "60 sec", tempo: "diep en gecontroleerd; volledig omhoog", intensity: "laatste rep 20–30 sec hold" } },
    "short-lever-copenhagen": { inputType: "seconds", secondsRange: { min: 10, max: 60, step: 5 }, protocol: { rest: "tijdens kantwissel", tempo: "statische hold", intensity: "voorzichtig starten; kan spierpijn geven" } },
    "iso-elbow-flexion-cuff": { inputType: "weight-seconds", weightRange: { min: 0, max: 60, step: 0.5 }, secondsRange: { min: 15, max: 60, step: 5 }, protocol: { rest: "30–45 sec", tempo: "statische hold", intensity: "week 1–2: 5–6/10; later 7–8/10" } },
    "slow-cable-elbow-flexion-cuff": { weightRange: { min: 0, max: 60, step: 0.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "45 sec", tempo: "2 sec omhoog, 1 sec vast, 3 sec omlaag", intensity: "RIR 3–4 naar RIR 2" } },
    "weighted-wrist-flexion": { weightRange: { min: 0, max: 30, step: 0.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "45 sec", tempo: "2 sec omhoog, 3–4 sec omlaag", intensity: "maximaal 2/10 bij progressie" } },
    "pronation-supination-lever": { weightRange: { min: 0, max: 15, step: 0.25 }, repRange: { min: 1, max: 20 }, protocol: { rest: "30–45 sec", tempo: "3 sec per richting", intensity: "korte hefboom als start" } },
    "face-pull": { weightRange: { min: 0, max: 100, step: 0.5 }, repRange: { min: 1, max: 20 }, protocol: { rest: "45 sec", tempo: "gecontroleerd heen en terug", intensity: "geen momentum of harde grip" } },
    "half-kneeling-landmine-press": { weightRange: { min: 0, max: 80, step: 0.5 }, repRange: { min: 1, max: 20 }, optional: true, protocol: { rest: "60–90 sec", tempo: "gecontroleerd drukken en zakken", intensity: "RIR 3–4" } },
    "machine-overhead-press-neutral": { weightRange: { min: 0, max: 120, step: 0.5 }, repRange: { min: 1, max: 20 }, optional: true, protocol: { rest: "60–90 sec", tempo: "2–3 sec zakken", intensity: "start RIR 4; later RIR 2–3" } },
  };

  const NAMES = {
    "warmup-bike-walk": "Rustig fietsen of wandelen",
    "bodyweight-squat": "Bodyweight squat",
    "glute-bridge": "Glute bridge",
    "scapular-push-up": "Scapular push-up",
    "hip-circles": "Gecontroleerde heupcirkels",
    "arm-circles": "Rustige armcirkels",
    "wall-slide-unweighted": "Wall slide zonder gewicht",
    "warmup-set-first-exercise": "Lichte opwarmset eerste oefening",
    "iso-cable-external-rotation": "Isometrische cable external rotation",
    "iso-wrist-flexion": "Isometrische polsflexie voor golferselleboog",
    "hack-squat-or-leg-press": "Hack squat of leg press",
    "hip-thrust-machine": "Hip thrustmachine",
    "leg-curl": "Seated of lying leg curl",
    "bulgarian-split-squat-smith": "Bulgarian split squat in Smith-machine",
    "seated-calf-raise": "Seated calf raise",
    "weighted-dead-bug": "Weighted dead bug",
    "cable-external-rotation-dynamic": "Cable external rotation — dynamisch",
    "serratus-wall-slide": "Serratus wall slide met foamroller en miniband",
    "incline-pushup-plus": "Incline push-up plus",
    "cable-scaption-cuffs": "Cable scaption met polsmanchetten",
    "rear-delt-fly-machine": "Rear-delt flymachine",
    "single-leg-leg-press": "Single-leg leg press",
    "step-up": "Step-up",
    "standing-calf-raise": "Standing calf raise",
    "short-lever-copenhagen": "Short-lever Copenhagen plank",
    "iso-elbow-flexion-cuff": "Isometrische elleboogflexie met kabel en polsmanchet",
    "slow-cable-elbow-flexion-cuff": "Slow cable elbow flexion met cuff",
    "weighted-wrist-flexion": "Weighted wrist flexion — langzaam dynamisch",
    "pronation-supination-lever": "Pronation/supination met hefboom",
    "face-pull": "Face pull met rope of cuffs",
    "half-kneeling-landmine-press": "Half-kneeling landmine press",
    "machine-overhead-press-neutral": "Machine overhead press met neutrale greep",
    "half-kneeling-hip-flexor-stretch": "Half-kneeling hip-flexor stretch",
    "couch-stretch": "Couch stretch",
    "90-90-hip-switches": "90/90 hip switches",
    "adductor-rock-back": "Adductor rock-back",
    "dynamic-hamstring-mobility": "Dynamische hamstringmobiliteit",
    "calf-stretch-straight-knee": "Kuitstretch met gestrekte knie",
    "calf-stretch-bent-knee": "Kuitstretch met gebogen knie",
    "open-book-rotation": "Open-book rotatie voor de bovenrug",
  };

  function exercise(id, planned, block, options = {}) {
    const meta = EXERCISE_META[id] || {};
    const details = EXERCISE_DETAILS[id];
    return {
      id,
      name: NAMES[id] || id,
      planned,
      block,
      inputType: options.inputType || meta.inputType || "weight-reps",
      weightRange: options.weightRange || meta.weightRange || { min: 0, max: 120, step: 0.5 },
      repRange: options.repRange || meta.repRange || { min: 1, max: 30 },
      secondsRange: options.secondsRange || meta.secondsRange || { min: 10, max: 120, step: 5 },
      choices: options.choices || meta.choices || [],
      protocol: options.protocol || meta.protocol || null,
      optional: Boolean(options.optional ?? meta.optional),
      statusLabel: options.statusLabel || "",
      details,
      info: details?.why || "Volgens het actieve schema uitvoeren.",
      tips: details?.cue || "Beweeg gecontroleerd.",
      warning: details?.painRules?.[0] || "Pas aan bij toenemende pijn.",
      alternatives: details?.alternatives || [],
    };
  }

  const DAY_1_EXERCISES = () => [
    exercise("warmup-bike-walk", "3 min", "Warming-up"),
    exercise("bodyweight-squat", "1×8", "Warming-up"),
    exercise("glute-bridge", "1×8", "Warming-up"),
    exercise("scapular-push-up", "1×8", "Warming-up"),
    exercise("hip-circles", "1×5/kant", "Warming-up"),
    exercise("iso-cable-external-rotation", "3×25–40 sec/kant", "Blok A — Isometrische basis"),
    exercise("iso-wrist-flexion", "3×30–45 sec/arm", "Blok A — Isometrische basis"),
    exercise("hack-squat-or-leg-press", "4×5–8", "Blok B — Hoofdkracht"),
    exercise("hip-thrust-machine", "3×6–10", "Blok C — Heupextensie"),
    exercise("leg-curl", "3×8–12", "Blok D — Hamstrings"),
    exercise("bulgarian-split-squat-smith", "2–3×6–10/been", "Blok E — Unilateraal"),
    exercise("seated-calf-raise", "3×8–12 + 15–25 sec hold", "Blok F — Kuiten"),
    exercise("weighted-dead-bug", "2–3×6–8/kant", "Core-finisher"),
  ];

  const DAY_2_EXERCISES = () => [
    exercise("arm-circles", "1×10/richting", "Warming-up"),
    exercise("scapular-push-up", "1×8", "Warming-up"),
    exercise("wall-slide-unweighted", "1×8", "Warming-up"),
    exercise("warmup-set-first-exercise", "1 lichte set", "Warming-up"),
    exercise("cable-external-rotation-dynamic", "3×8–15/arm", "Schouderkracht"),
    exercise("serratus-wall-slide", "3×8–12", "Schouderkracht"),
    exercise("incline-pushup-plus", "3×8–15", "Schouderkracht"),
    exercise("cable-scaption-cuffs", "3×10–15", "Schouderkracht"),
    exercise("rear-delt-fly-machine", "2–3×10–15", "Schouderkracht"),
  ];

  const DAY_3_EXERCISES = () => [
    exercise("single-leg-leg-press", "3×6–10/been", "Hardloopkracht"),
    exercise("step-up", "3×6–10/been", "Hardloopkracht"),
    exercise("leg-curl", "3×8–12", "Hardloopkracht"),
    exercise("standing-calf-raise", "3×6–10 + 20–30 sec hold", "Hardloopkracht"),
    exercise("short-lever-copenhagen", "2×15–30 sec/kant", "Hardloopkracht"),
  ];

  const DAY_4_EXERCISES = () => [
    exercise("iso-elbow-flexion-cuff", "3×25–40 sec/arm", "Elleboogflexoren"),
    exercise("slow-cable-elbow-flexion-cuff", "3×8–12/arm", "Elleboogflexoren"),
    exercise("weighted-wrist-flexion", "3×8–15/arm", "Golferselleboog"),
    exercise("pronation-supination-lever", "2–3×8–12/richting/arm", "Onderarmrotatie"),
    exercise("face-pull", "2–3×10–15", "Schouder"),
  ];

  function cardio(title, instruction, details) {
    return {
      title,
      instruction,
      outdoor: details.outdoor,
      notes: details.notes,
      totalDuration: details.totalDuration || "ongeveer 30 min",
      runType: details.runType,
      rpe: details.rpe,
      warmup: details.warmup,
      main: details.main,
      recovery: details.recovery,
      cooldown: details.cooldown,
      incline: details.incline || "0–1%",
      talkTest: details.talkTest || "Tijdens easy lopen volledige zinnen kunnen spreken.",
      condition: details.condition || "",
      alternative: details.alternative || "Bij klachten: volledig easy, korter of run-walk.",
      goal: details.goal,
      why: details.why,
      expectedFeel: details.expectedFeel,
      technique: details.technique,
      progression: details.progression,
    };
  }

  function runForDay2(programWeek) {
    if (programWeek <= 2) {
      return cardio("Easy Run", "30 min volledig easy op RPE 3–4", {
        runType: "Easy run",
        rpe: "3–4/10",
        warmup: "Eerste 5 minuten extra rustig.",
        main: "Daarna ontspannen easy blijven lopen.",
        recovery: "Niet nodig; de hele run is easy.",
        cooldown: "Laatste minuten rustig houden.",
        outdoor: "Praattempo; volledige zinnen mogelijk.",
        notes: "Geen verplicht tempo. Loopband 0–1%.",
        goal: "Loopritme en aerobe basis onderhouden zonder de schoudertraining of heup te overbelasten.",
        why: "In de kalibratiefase moeten alle runs voorspelbaar en makkelijk blijven.",
        expectedFeel: "Ontspannen, licht en controleerbaar.",
        technique: "Schouders los, korte rustige pas, niet stampen en niet achter een tempo aanjagen.",
        progression: "Week 1–2 blijft volledig easy. Pas vanaf week 3 kunnen conditionele strides worden toegevoegd.",
      });
    }
    return cardio("Easy Run + ontspannen versnellingen", "25 min easy; 4 × 20 sec ontspannen versnellen; 40 sec rustig joggen tussen versnellingen", {
      runType: "Easy + strides",
      rpe: "Easy 3–4/10; versnellingen snel en soepel, niet maximaal",
      warmup: "Eerste 5 minuten extra rustig binnen de 25 minuten easy.",
      main: "Na 25 minuten vier versnellingen van 20 seconden.",
      recovery: "40 seconden rustig joggen tussen de versnellingen.",
      cooldown: "Na de laatste versnelling rustig eindigen.",
      outdoor: "Versnel technisch soepel; geen sprint of hard vechten.",
      notes: "Alleen uitvoeren wanneer de heup twee weken stabiel is. Loopband 0–1%.",
      condition: "Alleen bij twee weken stabiele heup.",
      alternative: "Als de heup niet stabiel is: 30 minuten volledig easy of run-walk.",
      goal: "Looptechniek en lichte snelheid prikkelen zonder zware intervalbelasting.",
      why: "Vanaf week 3 mag een kleine neuromusculaire prikkel worden toegevoegd als de heupreactie betrouwbaar rustig is.",
      expectedFeel: "Snel en soepel met ruim controle; niet hijgen of vechten.",
      technique: "Ontspannen schouders, korte lichte passen, geleidelijk versnellen en vóór vormverlies stoppen.",
      progression: "Week 3–8 blijft 4 × 20 sec. Maak ze niet langer of maximaal; stabiliteit is de progressie.",
    });
  }

  function runForDay3(programWeek) {
    if (programWeek <= 2) {
      return cardio("Easy Run", "30 min easy op RPE 3–4", {
        runType: "Easy run",
        rpe: "3–4/10",
        warmup: "Eerste 5–8 minuten extra rustig.",
        main: "Easy blijven lopen.",
        recovery: "Niet nodig.",
        cooldown: "Rustig eindigen.",
        outdoor: "Volledige zinnen kunnen spreken.",
        notes: "Geen tempo forceren; bij voorste heuppijn easy of run-walk.",
        goal: "De tweede beenprikkel combineren met voorspelbaar easy loopvolume.",
        why: "Weken 1–2 kalibreren eerst de reactie op hardloopkracht plus lopen.",
        expectedFeel: "Makkelijk en technisch beheerst.",
        technique: "Romp lang, pas rustig, voeten stil neerzetten en niet overstriden.",
        progression: "Vanaf week 3 volgt pas een gecontroleerde snellere prikkel.",
      });
    }
    if (programWeek <= 4) {
      return cardio("Gecontroleerde 1-minuutblokken", "8 min easy; 6 × 1 min vlot op RPE 6; na iedere minuut 1 min rustig; 10 min easy", {
        runType: "Gecontroleerde tempoprikkel",
        rpe: "Vlotte stukken 6/10; herstel easy",
        warmup: "8 minuten easy.",
        main: "6 stukken van 1 minuut vlot op RPE 6.",
        recovery: "Na ieder vlot stuk 1 minuut rustig.",
        cooldown: "10 minuten easy.",
        outdoor: "Geen vaste snelheid; loop op gecontroleerd gevoel.",
        notes: "Geen maximale intervaltraining.",
        alternative: "Bij pijn voorin de heup: volledige easy run of run-walk.",
        goal: "Een eerste gecontroleerde snelheidsprikkel toevoegen zonder maximale intervalstress.",
        why: "Na twee kalibratieweken wordt de loopbelasting iets specifieker, maar techniek en tolerantie blijven leidend.",
        expectedFeel: "Stevig maar volledig beheerst; iedere herhaling moet vergelijkbaar blijven.",
        technique: "Versnel geleidelijk, houd de pas licht en vertraag zodra de houding moet compenseren.",
        progression: "Week 3–4 hetzelfde protocol. Niet extra herhalingen toevoegen.",
      });
    }
    return cardio("Gecontroleerde 4-minutenblokken", "7 min easy; 3 × 4 min gecontroleerd stevig op RPE 6–7; 2 min easy tussen de blokken; 5 min uitlopen", {
      runType: "Gecontroleerde tempoprikkel",
      rpe: "Snelle stukken 6–7/10; geen maximale interval",
      warmup: "7 minuten easy.",
      main: "3 stukken van 4 minuten gecontroleerd stevig.",
      recovery: "2 minuten easy tussen de stukken.",
      cooldown: "5 minuten rustig uitlopen.",
      outdoor: "Geen vaste km/u; iedere herhaling technisch beheerst.",
      notes: "Geen tempo forceren.",
      alternative: "Bij voorste heuppijn: volledig easy, korter of run-walk.",
      goal: "Langer gecontroleerd stevig lopen zonder van de training een test te maken.",
      why: "Weken 5–8 bouwen de duur van de vlotte stukken op, terwijl het totale loopblok rond dertig minuten blijft.",
      expectedFeel: "Stevig maar herhaalbaar; na het derde stuk nog technisch netjes.",
      technique: "Romp lang, pasfrequentie soepel, niet sprinten en herstel echt easy.",
      progression: "Week 5–8 blijft 3 × 4 min. Verbeter controle in plaats van extra snelheid of volume toe te voegen.",
    });
  }

  function runForDay4(programWeek) {
    if (programWeek <= 2) {
      return cardio("Easy Run", "30 min volledig easy op RPE 3–4", {
        runType: "Easy run",
        rpe: "3–4/10",
        warmup: "Eerste 5 minuten extra rustig.",
        main: "Volledig easy.",
        recovery: "Niet nodig.",
        cooldown: "Rustig eindigen.",
        outdoor: "Praattempo.",
        notes: "Geen tijdrit en geen vaste snelheid.",
        goal: "Een derde rustige loopprikkel toevoegen zonder de armrevalidatie of heup te overbelasten.",
        why: "In de kalibratiefase is voorspelbare, lage intensiteit belangrijker dan progressie binnen de run.",
        expectedFeel: "Ontspannen en makkelijk.",
        technique: "Armen los, schouders laag, natuurlijke pas en rustige ademhaling.",
        progression: "Vanaf week 3 mag alleen de laatste 10 minuten geleidelijk iets vlotter.",
      });
    }
    return cardio("Gecontroleerde progression run", "20 min easy; laatste 10 min geleidelijk iets vlotter tot maximaal RPE 5–6", {
      runType: "Progression run",
      rpe: "Eerste 20 min 3–4/10; einde maximaal 5–6/10",
      warmup: "Eerste 5 minuten extra rustig binnen de 20 minuten easy.",
      main: "Na 20 minuten geleidelijk versnellen.",
      recovery: "Geen losse herstelblokken; versnelling blijft continu en beheerst.",
      cooldown: "Laatste minuut zo nodig weer iets rustiger.",
      outdoor: "Geen tijdrit; tempo loopt alleen op zolang de techniek ontspannen blijft.",
      notes: "Gecontroleerde progression run.",
      alternative: "Bij vermoeidheid of heuppijn: alle 30 minuten easy of run-walk.",
      goal: "Leren iets vlotter te eindigen zonder maximale inspanning.",
      why: "Dit geeft vanaf week 3 een lichte progressieprikkel naast de specifiekere Dag-3-run.",
      expectedFeel: "Geleidelijk actiever, nooit buiten controle.",
      technique: "Versnel met pasritme en ontspanning, niet door grote passen of hard duwen.",
      progression: "Week 3–8 blijft maximaal RPE 5–6. Geen tijds- of tempojacht.",
    });
  }

  function phaseIdForProgramWeek(programWeek) {
    if (programWeek <= 2) return "fase-1";
    if (programWeek <= 5) return "fase-2";
    return "fase-3";
  }

  function isoDatePlusDays(startIso, days) {
    const [year, month, day] = startIso.split("-").map(Number);
    const date = new Date(year, month - 1, day);
    date.setDate(date.getDate() + days);
    return [
      date.getFullYear(),
      String(date.getMonth() + 1).padStart(2, "0"),
      String(date.getDate()).padStart(2, "0"),
    ].join("-");
  }

  function session(programWeek, number, title, type, exercises, cardioBlock, options) {
    return {
      sessionId: `${APP_CONFIG.planId}_w${programWeek}_d${number}`,
      sessionNumber: number,
      title,
      type,
      plannedOffset: options.plannedOffset,
      goal: options.goal,
      warmup: options.warmup,
      exercises,
      cardio: cardioBlock,
      notes: options.notes,
      infoBlocks: options.infoBlocks || [],
      estimatedDuration: options.estimatedDuration,
      displayExerciseCount: options.displayExerciseCount,
      strengthPhilosophy: options.strengthPhilosophy,
      runningPhilosophy: options.runningPhilosophy || "",
      combinationPhilosophy: options.combinationPhilosophy || "",
      goodDayAdvice: options.goodDayAdvice,
      tiredDayAdvice: options.tiredDayAdvice,
      focusLine: options.focusLine,
      placementAdvice: options.placementAdvice,
    };
  }

  function sessionsForWeek(programWeek) {
    const phaseId = phaseIdForProgramWeek(programWeek);
    const phaseRule = PHASES.find((phase) => phase.phaseId === phaseId)?.rules || "";
    return [
      session(programWeek, 1, "Dag 1 — Volledige krachttraining", "kracht + revalidatie", DAY_1_EXERCISES(), null, {
        plannedOffset: 0,
        estimatedDuration: "ongeveer 60 min",
        displayExerciseCount: 8,
        goal: "Zware beenkracht, peesbelasting, core en een gecontroleerde basisprikkel voor schouders en ellebogen.",
        warmup: "3 min fietsen/wandelen, 8 squats, 8 glute bridges, 8 scapular push-ups en 5 heupcirkels per kant.",
        notes: "Grote beenoefeningen technisch zwaar, meestal rond RIR 2; nooit tot spierfalen.",
        strengthPhilosophy: "De sessie begint met gecontroleerde schouder- en polsflexorholds en bouwt daarna op naar zware beenkracht, heupextensie, hamstrings, unilaterale controle, kuiten en core. Machines en de Smith-opstelling maken substantiële belasting mogelijk zonder onnodige gripbelasting.",
        goodDayAdvice: "Voer de geplande sets strakker uit en blijf binnen de fase-RIR. Verhoog alleen wanneer de bovengrens technisch goed is gehaald en de vorige reactie rustig was.",
        tiredDayAdvice: "Verlaag één variabele: gewicht, range, holdduur of sets. Houd de beweging herkenbaar en stop bij scherpe pijn, tintelingen of krachtverlies.",
        focusLine: "Serieuze belasting verdragen zonder techniek of volgende-ochtendherstel te verliezen.",
        placementAdvice: "Probeer tussen Dag 1 en Dag 3 minimaal één volledige dag te laten zitten.",
        infoBlocks: [{ title: "Faseregel", text: phaseRule }],
      }),
      session(programWeek, 2, "Dag 2 — Schouderkracht + Easy Run", "hybride", DAY_2_EXERCISES(), runForDay2(programWeek), {
        plannedOffset: 2,
        estimatedDuration: "ongeveer 60 min",
        displayExerciseCount: 5,
        goal: "Rotator-cuffkracht, serratusfunctie, gecontroleerd duwen, armheffen en achterste-schoudercontrole combineren met een easy run.",
        warmup: "10 armcirkels per richting, 8 scapular push-ups, 8 wall slides en één lichte opwarmset.",
        notes: programWeek >= 3 ? "Strides alleen bij twee weken stabiele heup." : "De run blijft volledig easy.",
        strengthPhilosophy: "External rotation, serratuswerk, push-up plus, scaption en rear delts trainen verschillende functies van de schouder. De schouderbladen mogen natuurlijk bewegen; ze worden niet geforceerd vastgezet.",
        runningPhilosophy: runForDay2(programWeek).goal,
        combinationPhilosophy: "De schoudertraining belast de benen nauwelijks. Daardoor kan de easy run erna loopritme toevoegen zonder de zware beendagen direct te stapelen.",
        goodDayAdvice: "Maak de schouderuitvoering nauwkeuriger. Houd de run easy; conditionele versnellingen blijven soepel en nooit maximaal.",
        tiredDayAdvice: "Gebruik cuffs, minder range of lichtere kabel. Maak de run volledig easy, korter of run-walk.",
        focusLine: "Schoudercontrole opbouwen en ontspannen lopen.",
        placementAdvice: "Standaard op woensdag; verschuiven mag zolang herstel en volgorde logisch blijven.",
        infoBlocks: [{ title: "Faseregel", text: phaseRule }],
      }),
      session(programWeek, 3, "Dag 3 — Hardloopkracht + Hardlopen", "hybride", DAY_3_EXERCISES(), runForDay3(programWeek), {
        plannedOffset: 4,
        estimatedDuration: "ongeveer 60 min",
        displayExerciseCount: 5,
        goal: "Unilaterale beenkracht, hamstrings, kuiten en adductoren trainen vóór een gecontroleerde loopprikkel.",
        warmup: "Gebruik de eerste lichte set van de single-leg leg press als technische voorbereiding.",
        notes: "Bij pijn aan de voorzijde van de heup: volledige easy run of run-walk; geen tempo forceren.",
        strengthPhilosophy: "De oefeningen leggen een tweede serieuze beenprikkel op éénbenige kracht, bekkencontrole, hamstrings, kuit/Achilles en adductoren. De belasting mag zwaar worden, maar de run moet technisch uitvoerbaar blijven.",
        runningPhilosophy: runForDay3(programWeek).goal,
        combinationPhilosophy: "Kracht en lopen staan bewust samen: dit is de specifieke hardloopkrachtdag. Dag 1 ligt minimaal één volledige dag eerder zodat de benen niet zonder herstel opnieuw zwaar worden belast.",
        goodDayAdvice: "Houd RIR en RPE exact aan. Maak de snelle stukken gelijkmatiger, niet sneller of langer.",
        tiredDayAdvice: "Verminder krachtvolume en maak de run easy of run-walk. Voorste-heuppijn is geen signaal om tempo te bewijzen.",
        focusLine: "Sterke benen en technisch gecontroleerde loopbelasting.",
        placementAdvice: "Houd minimaal één volledige dag tussen Dag 1 en Dag 3.",
        infoBlocks: [{ title: "Faseregel", text: phaseRule }],
      }),
      session(programWeek, 4, "Dag 4 — Ellebogen, brachialis, schouder + Run", "hybride", DAY_4_EXERCISES(), runForDay4(programWeek), {
        plannedOffset: 6,
        estimatedDuration: "ongeveer 60 min",
        displayExerciseCount: 5,
        goal: "Golfersellebogen, brachialis/elleboogflexoren en schouders progressief belasten en afsluiten met een beheerste run.",
        warmup: "Eén lichte proefset/hold van de eerste oefening; schouder en pols rustig bewegen.",
        notes: "De pijnbron rond brachialis/distale biceps kan op afstand niet worden vastgesteld. Geen pull-up-testen binnen dit blok.",
        strengthPhilosophy: "De cuff scheidt elleboogflexie van harde grip. Isometrische en dynamische flexie, polsflexie en onderarmrotatie bouwen samen de belastbaarheid op; face pulls voegen schouder- en bovenrugcontrole toe.",
        runningPhilosophy: runForDay4(programWeek).goal,
        combinationPhilosophy: "De revalidatiekracht vraagt weinig beenvermoeidheid. Daardoor kan de derde run worden toegevoegd zonder een extra zware lower-bodysessie.",
        goodDayAdvice: "Verhoog alleen volgens hold- of dubbele progressie. De run mag geleidelijk vlotter, maar blijft geen tijdrit.",
        tiredDayAdvice: "Gebruik cuff, kortere range of lichtere hefboom. Houd de run volledig easy of kies run-walk.",
        focusLine: "Elleboog- en schouderbelasting opbouwen zonder grip of loopsnelheid te forceren.",
        placementAdvice: "Standaard op zondag. Houd de run beheerst zodat de nieuwe week niet met restvermoeidheid begint.",
        infoBlocks: [{ title: "Faseregel", text: phaseRule }],
      }),
    ];
  }

  const WEEK_FOCUS = {
    1: "Kalibreer techniek, pijnreactie en startgewichten. Alle runs blijven easy en geen enkele oefening hoeft maximaal te voelen.",
    2: "Bevestig dat de gekozen belasting de volgende ochtend terugkeert naar het oude uitgangsniveau. Nog geen overhead press.",
    3: "Bouw dynamische weerstand op. Conditionele strides en de eerste 1-minuutblokken verschijnen alleen als de heup stabiel is.",
    4: "Maak holds stabieler en werk richting RIR 2–3. Een neutrale grip of landmine press is alleen een test na behaalde criteria.",
    5: "De snellere Dag-3-run groeit naar drie stukken van vier minuten. Controle blijft belangrijker dan tempo.",
    6: "Grote beenoefeningen en kleine dynamische oefeningen gaan richting RIR 2. Grip mag geleidelijk terugkomen.",
    7: "Bouw substantiële belastbaarheid op zonder maximale pull-ups, vrije rows of curls te testen.",
    8: "Rond het fundamentblok technisch sterk af en beoordeel wat stabiel genoeg is voor het nieuwe marathonspecifieke vervolgplan.",
  };

  const WEEKS = Array.from({ length: 8 }, (_, index) => {
    const programWeek = index + 1;
    const calendarWeek = 31 + index;
    const phaseId = phaseIdForProgramWeek(programWeek);
    const startDate = isoDatePlusDays(APP_CONFIG.startDate, index * 7);
    const endDate = isoDatePlusDays(startDate, 6);
    return {
      planId: APP_CONFIG.planId,
      planVersion: APP_CONFIG.planVersion,
      phaseId,
      programWeek,
      calendarWeek,
      label: `Week ${programWeek}`,
      startDate,
      endDate,
      sessions: sessionsForWeek(programWeek),
      focus: WEEK_FOCUS[programWeek],
      attention:
        "Gebruik de 0–5/10-pijnschaal en controleer de volgende ochtend. Bij duidelijke toename was de totale dosis te groot.",
      runProgression:
        programWeek <= 2
          ? "Alle drie de runs volledig easy."
          : programWeek <= 4
            ? "Dag 2 conditionele strides, Dag 3 6 × 1 min vlot en Dag 4 gecontroleerd progressief."
            : "Dag 2 conditionele strides, Dag 3 3 × 4 min gecontroleerd en Dag 4 gecontroleerd progressief.",
    };
  });

  const MOBILITY_EXERCISES = [
    exercise("half-kneeling-hip-flexor-stretch", "2×30–45 sec/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
    exercise("couch-stretch", "2×30–45 sec/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
    exercise("90-90-hip-switches", "2×6–10/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
    exercise("adductor-rock-back", "2×8–12/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
    exercise("dynamic-hamstring-mobility", "2×8/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
    exercise("calf-stretch-straight-knee", "2×30 sec/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
    exercise("calf-stretch-bent-knee", "2×30 sec/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
    exercise("open-book-rotation", "2×6–8/kant", "Mobiliteit", { inputType: "none", optional: true, statusLabel: "Optioneel" }),
  ];

  const OVERHEAD_RETURN = {
    title: "Terugkeer naar overhead press",
    subtitle: "Optioneel — alleen bij stabiele klachten",
    conditions: [
      { id: "shoulder-stable", label: "Schoudertraining verloopt twee weken stabiel" },
      { id: "pushup-pain", label: "Incline push-up geeft maximaal 2/10 pijn" },
      { id: "next-morning", label: "Geen extra napijn de volgende ochtend" },
      { id: "no-weakness", label: "Geen onverwacht krachtverlies" },
    ],
    note: "Deze checklist is geen medische goedkeuring. Hij helpt alleen voorkomen dat de terugkeerstap te vroeg als gewone verplichte oefening wordt gezien.",
    exercises: [
      exercise("half-kneeling-landmine-press", "2–3×8–12 · RIR 3–4", "Eerste terugkeerstap", { optional: true, statusLabel: "Eerste terugkeerstap" }),
      exercise("machine-overhead-press-neutral", "start 2×10–12 · RIR 4", "Tweede terugkeerstap", { optional: true, statusLabel: "Na 2 stabiele landmineweken" }),
    ],
  };

  const TRAINING_PLAN = PHASES.map((phase) => ({
    ...phase,
    weeks: WEEKS.filter((week) => week.phaseId === phase.phaseId),
  }));

  window.APP_CONFIG = APP_CONFIG;
  window.GENERAL_TRAINING_RULES = GENERAL_RULES;
  window.TRAINING_PLAN = TRAINING_PLAN;
  window.TRAINING_WEEKS = WEEKS;
  window.REHAB_REFERENCE = {
    mobility: {
      title: "Mobiliteitsroutine",
      labels: ["Optioneel", "3–5× per week", "Buiten training", "15–20 min"],
      intro:
        "Deze routine ondersteunt bewegingsruimte en controle, maar vervangt de progressieve krachttraining niet. Voer hem buiten de vier hoofdsessies uit.",
      exercises: MOBILITY_EXERCISES,
    },
    overhead: OVERHEAD_RETURN,
  };
})();
